### ISSUE TITLE
Package it as mobile browser addons

### ISSUE THREAD

**Issue by notpushkin** [liriliri/eruda#101]
Hey there, thank you for the great work! Very useful to debug things on the go :)

Have you considered packaging it as an addon for mobile browsers that have addons support (at least [Firefox] and [Yandex.Browser], a Chrome derivative)? This would allow doing some advanced things that are otherwise disallowed due to the browser security model (i. e. capture requests happening in iframes of different origin). Let me know what you think!

[Firefox]: https://www.mozilla.org/en-US/firefox/mobile/
[Yandex.Browser]: https://play.google.com/store/apps/details?id=com.yandex.browser

**Comment by Killfrra** [comment]
I made a userscript version of eruda.min.js
It can be installed via a browser add-on such as Violentmonkey
https://openuserjs.org/scripts/Killfrra/eruda

**Comment by surunzi** [comment]
I developed this tool originally for testing pages whether they're running successfully in mobile browsers, especially embedded webview in different apps. In that case, it has to be able to run in all kinds of browsers(webviews) in order to suit my needs.
