### ISSUE TITLE
whatwg-fetch发起的fetch请求看不到response的内容体

### ISSUE THREAD

**Issue by Lyfme** [liriliri/eruda#104]
window.fetch发起的请求是能看到返回值的，但是用whatwg-fetch发起的请求看不到。希望能解答一下。

**Comment by surunzi** [comment]
有示例网页吗？

**Comment by hxdyj** [comment]
我的也是

**Comment by surunzi** [comment]
试下 v1.5.7

**Comment by hxdyj** [comment]
还是不行呀

**Comment by surunzi** [comment]
@hxdyj 给下示例页面，不然没法定位

**Comment by hxdyj** [comment]
ok啦，刚才有缓存，谢谢啦~

**Comment by aizigao** [comment]
我现在用的1.10.2, 用的是whatwg-fetch，现在也是看不到请求的说
![image](https://user-images.githubusercontent.com/14126445/69049780-9eb17680-0a3b-11ea-9511-4743b2a0d7dc.png)
