### ISSUE TITLE
Can you open https://eruda.liriliri.io/ web site source ?

### ISSUE THREAD

**Issue by bilibiliou** [liriliri/eruda#106]
![image](https://user-images.githubusercontent.com/12696061/59549395-6b9c2000-8f8f-11e9-8e00-b91c265ac3f1.png)

Can you show us about this canvas animation effect ?

**Comment by surunzi** [comment]
Source of the website: https://github.com/liriliri/freya
Source of the js effect: https://codepen.io/towc/pen/mJzOWJ/

**Comment by bilibiliou** [comment]
THX !!!
