### ISSUE TITLE
Use Eruda on a page not mine?

### ISSUE THREAD

**Issue by ramtob** [liriliri/eruda#11]
Hello, thanks for a much needed tool. How can I use Eruda on a page which is not mine (so that I cannot write a script inside)? TIA

**Comment by ramtob** [comment]
I tried the enter the following command for a url, but it did nothing..

javascript:(function () { var script = document.createElement('script'); script.src="//liriliri.github.io/eruda/eruda.min.js"; document.body.appendChild(script); script.onload = function () { eruda.init() } })();

**Comment by surunzi** [comment]
If you're using chrome mobile, getting rid of the IIFE wrapper should work.
```javascript
javascript:var script = document.createElement('script'); script.src="//liriliri.github.io/eruda/eruda.min.js"; document.body.appendChild(script); script.onload = function () { eruda.init() };
```
As for safari, it is not allowed to run JavaScript directly from address bar:(

**Comment by ramtob** [comment]
I've tried entering this expression as url on three Android browsers
(Android browser, Chrome, Firefox), but it didn't work.
בתאריך 5 ביונ' 2016 14:19,‏ "RedHoodSu" <notifications@github.com> כתב:

**Comment by surunzi** [comment]
Does it work just entering `javascript:alert('test')`?
PS: When you copy paste the code into chrome address bar, it will remove **javascript:** prefix. Try to add it back manually.

**Comment by ramtob** [comment]
javascript:alert('test') works in Android browser and chrome. In Firefox it
doesn't, but it does work when put as bookmark.

I also tried putting the Eroda "javascript:" command as bookmark. Still
doesn't work. On Android browser and Chrome, no response. On Firefox it
displays "function () { eruda.init() }" on an orherwise blank page.
בתאריך 6 ביונ' 2016 06:28,‏ "RedHoodSu" <notifications@github.com> כתב:

**Comment by surunzi** [comment]
I tried with only chrome mobile.
In my case, for android:
Putting in address bar dose work, but bookmark doesn't, even with simple `javascript:alert('test')`;
For chrome ios:
Both ways are fine to use.

Obviously, mobile browsers refuse to execute javascript urls under certain circumstances. And there is nothing we can do about it:(

**Comment by ramtob** [comment]
You're right, in chrome for android it works as url. You need to readd the
word "javascript:" - good tip!
בתאריך 6 ביונ' 2016 10:36,‏ "RedHoodSu" <notifications@github.com> כתב:

**Comment by Peculiar-codes** [comment]
Ffff

> If you're using chrome mobile, getting rid of the IIFE wrapper should work.
> 
> ```js
> javascript:var script = document.createElement('script'); script.src="//liriliri.github.io/eruda/eruda.min.js"; document.body.appendChild(script); script.onload = function () { eruda.init() };
> ```
> 
> As for safari, it is not allowed to run JavaScript directly from address bar:(

Nothing happens after that, though alert works fine

**Comment by cfuendev** [comment]
Just a heads up based on my experience recently. Chrome mobile removes the "javascript:" prefix on paste, leaving just the JS code in the url with no instruction to run it, which then takes you straight to google search instead of running it. Maybe make sure that the prefix is present?

Not sure if this could be what anyone here is experiencing since everyone here describes the behavior as ..

> Nothing happens after that

.. contrary to what my Android Chrome did, which is sending me to google search results after the script is set as the URL.
