### ISSUE TITLE
Editing page elements

### ISSUE THREAD

**Issue by hjyoung1** [liriliri/eruda#110]
It would be great if editing page elements like (html + css) become possible.
Currently with edit page snippet only text is allowed to edited.
Thanks for creating and actively working on this project.

**Comment by surunzi** [comment]
Duplicate of #25

**Comment by NguyenThanh1995** [comment]
I have updated it so you can fix all CSS including @media, styles, @keyframes ... I'm waiting for the author to merge it. 😄 You are the reason I made this upgrade
