### ISSUE TITLE
生产环境报错

### ISSUE THREAD

**Issue by Joyeuxman** [liriliri/eruda#113]
![image](https://user-images.githubusercontent.com/21262781/62361718-1ff90200-b54e-11e9-8f86-00b50e71736d.png)
![image](https://user-images.githubusercontent.com/21262781/62361748-2f784b00-b54e-11e9-8c44-9484bcb1060f.png)
1. 通过script方式引入，开发、生产环境都OK
2. 通过import引入，开发环境OK，生产环境报错
3. 引入方式如下(main.js)
```
import eruda from 'eruda'
eruda.init()
```

**Comment by surunzi** [comment]
Duplicate of #108
