### ISSUE TITLE
network看不到具体的header和param参数，点击某一行也没反应

### ISSUE THREAD

**Issue by WeiChuanJia** [liriliri/eruda#117]
[截图](https://pic.newbanker.cn/img/2401/2019/9/18/54c568a4c14541f1ac4b9a98b0c38d3f.jpeg)

**Comment by surunzi** [comment]
是在特定机型上出错还是特定网页上出错？

**Comment by K-walker** [comment]
@surunzi  我这边也是同样问题。看不到请求头数据，我用chrome测试的

**Comment by K-walker** [comment]
@surunzi 
![WeWork Helper20190927113351](https://user-images.githubusercontent.com/10557092/65740305-cb6f9e80-e11a-11e9-80ff-0af13e96afa5.png)

Request Headers 没有打印出来，麻烦帮忙看看吧，谢谢了

**Comment by surunzi** [comment]
request header 目前没有办法获取到，这里展示的只是你自己设置的 request 头部（浏览器自己加上的拿不到）

**Comment by K-walker** [comment]
@surunzi  但是我那个header的 authorization 这个字段是自己设置的，也拿不到啊
![image](https://user-images.githubusercontent.com/10557092/65740491-826c1a00-e11b-11e9-8786-6723f7392a02.png)

**Comment by surunzi** [comment]
@K-walker 给个示例网页

**Comment by K-walker** [comment]
@surunzi  稍等

**Comment by K-walker** [comment]
@surunzi 你有QQ吗？我直接给你我们公司测试地址网址吧，账号密码在这不方便发 1397353597
