### ISSUE TITLE
对默认的 shadowroot host 元素应用 CSS 重设样式 all: initial !important

### ISSUE THREAD

**Issue by Crystal-RainSlide** [liriliri/eruda#119]
一些例如 https://example.com 之类的网站/页面中含有适用于 `div`  甚至 `*` 的样式，最终可导致 eruda 的 shadowroot host 元素，插在页面末端的 `<div>`，变为可见，如下图左侧：
![图片](https://user-images.githubusercontent.com/16851802/65818199-ef79cf80-e241-11e9-9264-1415ad72ab6e.png)
对其应用
```css
{ all: initial !important; }
```
可以有效清除那些样式的干扰。

IE / Edge 不支持，Chrome 37+，Firefox 27+，Safari 9.1+，Safari Mobile 9.3+

ref: https://developer.mozilla.org/zh-CN/docs/Web/CSS/all

**Comment by surunzi** [comment]
1.6.2 修复

**Comment by Crystal-RainSlide** [comment]
感谢
