### ISSUE TITLE
默认初始化，但是加载面板的数量有问题

### ISSUE THREAD

**Issue by tenbamboo** [liriliri/eruda#12]
前提：
我是通过jquery.getScript()引入的工具。

问题：

多个页面，加载工具的代码一致，但是有时候加载的面板数量不一致。

有时 全都加载进来了
有时只有 Source,Info,Snippets,Features,Settings

**Comment by surunzi** [comment]
根据描述无法明确原因，可以确定下发生的条件吗？
比如：是否跟getScript有关？是否跟不同页面有关？是否跟浏览器有关？
try {eruda.init();} catch (e) {alert(e.message)}; 看下加载面板少时是否有报错。

**Comment by tenbamboo** [comment]
工具自己写到 localStorage 中的信息， 会对下一次加载有影响吗

**Comment by surunzi** [comment]
会的，设置会保存到localStorage里面，下一次初始化会读取。是webview不支持localStorage吗？

**Comment by tenbamboo** [comment]
我猜可能是这个原因，因为看到localStorage 会设置值，具体是哪个key 会影响到面板的数量？

**Comment by surunzi** [comment]
每个面板的设置都会有自己的key，eruda-console，eruda-network等，看起来是那些有配置项的面板都挂了。

**Comment by surunzi** [comment]
@tenbamboo 确认下是不是因为webview不支持localStorage导致的？

**Comment by tenbamboo** [comment]
在微信公众号里看，应该是支持的，我自己的数据都在localStorage跑

**Comment by surunzi** [comment]
Try catch有alert出来什么错误信息吗？

**Comment by tenbamboo** [comment]
null is not an object(evaluating'e.length')

**Comment by surunzi** [comment]
用下未压缩的版本，看能不能知道e是什么？

**Comment by tenbamboo** [comment]
好用了，方法是我直接在工具加载成功的页面中，打开console ，然后直接输入localStorage.clear();
然后再打开问题页面就没问题了，所有工具都加载上来了，但是这可能是缓兵之计吧，具体再看

**Comment by tenbamboo** [comment]
现在不能还原事故现场了。。。不好意思。。。
