### ISSUE TITLE
Invalid characters in console

### ISSUE THREAD

**Issue by kmisha** [liriliri/eruda#123]
While typing a string literal I use a single (') or double (") quotes. For example: `var test = "test"` But on IOS devices I got invalid character message after executing.

![bug](https://user-images.githubusercontent.com/8425363/66746374-b755cc00-ee92-11e9-9603-75e43cb442ce.jpg)

**Comment by surunzi** [comment]
https://en.wikipedia.org/wiki/Quotation_mark Use straight quotes instead of curly quotes.

![screenshot](https://user-images.githubusercontent.com/3487535/66749032-5393c900-eebb-11e9-8c3c-144b6d7adcde.jpg)
