### ISSUE TITLE
Long press to copy text

### ISSUE THREAD

**Issue by hjyoung1** [liriliri/eruda#124]
Long press to copy text not working properly.
Check below gif. 
This happens on other part too (like sources, dom etc) 
![ScreenRec_20191018_012343_00](https://user-images.githubusercontent.com/45882061/67043204-33783a00-f147-11e9-88f6-35854d913525.gif)

**Comment by surunzi** [comment]
Copy is disabled by default, only a few parts are allowed to copy stuff,  console, for example.

I'll make the url in image view copyable.

**Comment by surunzi** [comment]
I just found out it is already copyable on my phone, try another browser and see if it's working?

**Comment by hjyoung1** [comment]
Unfortunately no, i tried brave, chrome, chrome canary, opera, kiwi browser. Copy is not working it selects main page text.
I'm running Android pie. 
![Screenshot_20191018_104014](https://user-images.githubusercontent.com/45882061/67067407-f1c1b080-f193-11e9-94b3-14adfdfd077e.png)

**Comment by surunzi** [comment]
[eruda.zip](https://github.com/liriliri/eruda/files/3746747/eruda.zip) I deleted the css that disables copy, download the file and see if it works.

**Comment by hjyoung1** [comment]
No resources view image url is still not copyable.  It selects main page text :/

**Comment by surunzi** [comment]
Then I have no idea what is causing the bug. It would be appreciated if you can fix the issue and make a pr since I can't reproduce it myself.

**Comment by surunzi** [comment]
Closing it since no one has reported the same issue.
