### ISSUE TITLE
Network 面板跳转 Resources 面板问题

### ISSUE THREAD

**Issue by iUUCoder** [liriliri/eruda#126]
正常情况下，在 Network 面板能够看到页面中发送的所有请求列表，点击列表项，会跳转到 Resources 面板，展示该请求的详细信息。

但是，若同时使用了 GrowingIO 这类无埋点统计方案，就会遇到问题。

在点击列表项的时候，统计 SDK 会立即发送一次请求，Network 列表会立即全量刷新，且没有跳转到 Resources，这样就看不到请求的详细信息了。

这可能是一个个例，或许通过修改 Eruda 配置/设置就能解决，希望熟悉 Eruda 的大佬或作者给出指导，谢谢！

**Comment by surunzi** [comment]
#103 
```javascript
let el = document.createElement('div');
el.setAttribute('growing-ignore', true);
document.body.appendChild(el);

eruda.init({
    container: el,
    tool: ['console', 'elements']
});
```
