### ISSUE TITLE
Info菜单下url参数&reg显示成了图标

### ISSUE THREAD

**Issue by flyerH** [liriliri/eruda#127]
原本的字符串是这个
![image](https://user-images.githubusercontent.com/17452527/68367775-683d4700-0171-11ea-969a-1ced5cd0001e.png)

在Info菜单的Location里显示成了这样
![image](https://user-images.githubusercontent.com/17452527/68367723-4ba10f00-0171-11ea-917f-324feeaddb3c.png)

**Comment by surunzi** [comment]
1.10.3 修复了。
