### ISSUE TITLE
统一/整理 eruda 内使用的 CSS 选择器，同时提供一些标准组件

### ISSUE THREAD

**Issue by Crystal-RainSlide** [liriliri/eruda#128]
对 eruda 进行开发时，可以通过更改例如 [variable.scss](https://github.com/liriliri/eruda/blob/master/src/style/variable.scss) 等 scss 源文件来高效地修改。但是，如果选择使用官方版本并自行附加 CSS，那么，由于最终的 CSS 选择器是各个组件独立生成的，修改效率会非常低：

![选择器](https://user-images.githubusercontent.com/16851802/68658374-47f5f980-0570-11ea-8c84-38f407125cc9.png)

如果在生成选择器的基础上，将常用常见的组件，如卡片、按钮，整理成拥有固定类名的标准组件，就可以基本解决问题。除却方便撰写额外样式，这么做还可以减少生成的 CSS 的长度，也能为插件预置一些常用组件的类名与样式，方便插件的开发。

另外，建议将一些元素的字体设为等宽字体。
目前，我收集到这些：
```
.eruda-console-container .eruda-logs-container,
.eruda-elements .eruda-parents,
.eruda-elements .eruda-breadcrumb,
.eruda-elements .eruda-children,
.eruda-elements .eruda-section > h2 ~ div,
.eruda-network .eruda-requests,
.eruda-info.eruda-tool li .eruda-content {
	font-family: Fira Code, Menlo, Monaco, Consolas, Liberation Mono, Courier New, Courier, monospace;
}
```

**Comment by surunzi** [comment]
不太懂这里的意义，所以你是写插件，同时这个插件是拿内置的某个插件更改的吗。。

**Comment by Crystal-RainSlide** [comment]
我目前主要只是改改 eruda 的样式，插入一个 `<style>`，来更改 eruda 中不同 Tab 内类似元素的样式。这段代码暂时和加载 eruda 的代码放在一起，没有写插件实现。

``` JavaScript
eruda._shadowRoot.appendChild( (() => {
  const style = document.createElement("style");
  const _ = ".eruda-dev-tools .eruda-tools";
  style.textContent =
`${_} .eruda-not-supported { border-radius: 2px !important; }
 ${_} ...`;
  return style;
})() );
```

总之，因为想使用官方版本，所以没有办法更改原始 SCSS 文件。而现在 eruda 最终产生的 CSS 类名和选择器没有统一，附加样式编写起来太难了。

以后，如果顺利的话，我打算给 eruda 写一个自定义样式插件，类似 Firefox 开发者工具的样式编辑器，允许往 eruda 或当前页面中临时加入 CSS 样式。

**Comment by surunzi** [comment]
目前各个插件共用的样式很少，抽公共组件的意义不大。

**Comment by Crystal-RainSlide** [comment]
好吧，就先这样吧

**Comment by surunzi** [comment]
2.0.0 版本已经内置了多种主题样式。
