### ISSUE TITLE
network捕获不到请求

### ISSUE THREAD

**Issue by FLanvendar** [liriliri/eruda#134]
本地调试时，network可以看到请求，
但是发到测试环境之后，network的请求是空的。
用的是dva的fetch方法

**Comment by surunzi** [comment]
有线上 demo 吗？

**Comment by gujiwuqing** [comment]
一样 获取不到

**Comment by dovahkiin1225** [comment]
你这是fetch请求吧？然后还是重写了fetch请求？
我现在也遇到了这么个情况。

**Comment by surunzi** [comment]
新版应该修复了这个问题。
