### ISSUE TITLE
suggestion-editing/deleting elements

### ISSUE THREAD

**Issue by dayoshiguy** [liriliri/eruda#137]
Can you please add the ability to edit the innerHTML() of elements in the "Elements" or "DOM" panel?  This would include the ability to delete elements etc.  I think this is the only major feature that this is missing

**Comment by surunzi** [comment]
Currently working on https://github.com/liriliri/chii, try and see if it suits your needs.

**Comment by dayoshiguy** [comment]
cool!

**Comment by surunzi** [comment]
Use https://github.com/liriliri/chii if you do need to edit elements.
