### ISSUE TITLE
[feature] Check/uncheck and add additional style properties

### ISSUE THREAD

**Issue by dvlden** [liriliri/eruda#139]
I am not sure if this is already possible somehow, but mimic actual dev-tools functionality from the desktop. 

- Toggle check of a property
- Add additional properties

Just a thought, I searched through the closed issues, but couldn't find anything regarding this.

Great work, I was looking for something like this for years! 🔥

**Comment by surunzi** [comment]
Currently working on https://github.com/liriliri/chii, try and see if it suits your needs.

**Comment by surunzi** [comment]
Use https://github.com/liriliri/chii if you do need to edit element styles.
