### ISSUE TITLE
Set default settings in "init"

### ISSUE THREAD

**Issue by FeBe95** [liriliri/eruda#141]
A nice enhancement for this project could be the possibility to set custom default settings while initializing eruda, by adding a `settings` object next to `container` and `tool`. It could contain key/value pairs such as `theme: 'Monokai Pro'` and `display-size: 50` etc.

**Comment by surunzi** [comment]
version 2.4.0
```javascript
eruda.init({
  defaults: {
    displaySize: 50,
    transparency: 0.9,
    theme: 'Monokai Pro'
  }
})
```

**Comment by Lruihao** [comment]
@surunzi  Excuse me, How can I to set the theme in the code?

**Comment by RuralAnemone** [comment]
is it possible to set more than just those 3 settings? if so, what are they called?

**Comment by Dhyfer1** [comment]
> version 2.4.0
> 
> ```js
> eruda.init({
>   defaults: {
>     displaySize: 50,
>     transparency: 0.9,
>     theme: 'Monokai Pro'
>   }
> })
> ```

@surunzi In the latest version 2.11.3 I would like to change the size of diplay to 50, but I don't know where to put it in the new version. Can you help me?

Where I place `display-size: 50` in this script from the latest version?
```js
javascript:(function () { var script = document.createElement('script'); script.src="//cdn.jsdelivr.net/npm/eruda"; document.body.appendChild(script); script.onload = function () { eruda.init() } })();
```
