### ISSUE TITLE
Not working for google colab 

### ISSUE THREAD

**Issue by xd003** [liriliri/eruda#143]
Eruda works for in every website pretty good
But when i try it in google colab - https://colab.research.google.com

It doesn't works and no icon shows at in bottom unlike other websites

**Comment by surunzi** [comment]
Same reason as #75, evaluate `define = null` first before injecting script since the website is using amd.

**Comment by MasterInQuestion** [comment]
See also:
    https://dev.to/iggredible/what-the-heck-are-cjs-amd-umd-and-esm-ikm
    https://www.google.com/search?hl=en&gl=ca&num=10&q=JavaScript+AMD

    Simply put:
    JavaScript allows rewriting certain pre-defined language features.
    And the rewritten "define" somehow appeared unexpected to Eruda.
