### ISSUE TITLE
请问下，不能在微信小程序中使用吗？

### ISSUE THREAD

**Issue by huangche007** [liriliri/eruda#157]
现在在通过mpvue框架进行微信小程序的开发，在微信企业小程序端部分手机没有开发调试面板，就网上看了这个库还不错，准备用一下，发现用不了。

我的使用方式，在index.html中直接引入：

    <script src="https//cdn.jsdelivr.net/npm/eruda"></script>
    <script>eruda.init();</script>

发现不行，难道是我使用的方式不对？

**Comment by surunzi** [comment]
小程序中用不了。

**Comment by huangche007** [comment]
@surunzi ok,thx

**Comment by cyb233** [comment]
微信本身应该是可以在x5内核中开启vConsole的吧，在微信打开debugx5.qq.com
