### ISSUE TITLE
Add Shadow DOM support to Elements tab

### ISSUE THREAD

**Issue by CaterpyOwO** [liriliri/eruda#158]
I think, it'd be a great enhancement if we could inspect the shadowRoot on HTML elements, as currently it is completely unsupported by eruda.

**Comment by uplusion23** [comment]
I haven't gotten too much into Eruda's structure, or how it builds the UI elements, but the areas I see that catch my attention are 
[Line 115](https://github.com/liriliri/eruda-dom/blob/master/src/index.js#L115) in Eruda-DOM/index.js, and [Line 291](https://github.com/liriliri/eruda/blob/master/src/Elements/Elements.js#L291) in Eruda/Elements.js.

The code can be adjusted as follows;

eruda-dom/src/index.js [Line 115](https://github.com/liriliri/eruda-dom/blob/master/src/index.js#L115)
```javascript
// From
const childCount = child.childNodes.length;
// To
const childCount = (!child.shadowRoot) ? child.childNodes.length : child.shadowRoot.childNodes.length;
```

eruda/src/Elements/Elements.js [Line 291](https://github.com/liriliri/eruda/blob/master/src/Elements/Elements.js#L291)
```javascript
ret.children = formatChildNodes(el.childNodes)

ret.children = formatChildNodes((!el.shadowRoot) ? el.childNodes : el.shadowRoot.childNodes);
```

**Comment by uplusion23** [comment]
> I haven't gotten too much into Eruda's structure, or how it builds the UI elements, but the areas I see that catch my attention are
> [Line 115](https://github.com/liriliri/eruda-dom/blob/master/src/index.js#L115) in Eruda-DOM/index.js, and [Line 291](https://github.com/liriliri/eruda/blob/master/src/Elements/Elements.js#L291) in Eruda/Elements.js.
> 
> The code can be adjusted as follows;
> 
> eruda-dom/src/index.js [Line 115](https://github.com/liriliri/eruda-dom/blob/master/src/index.js#L115)
> 
> ```js
> // From
> const childCount = child.childNodes.length;
> // To
> const childCount = (!child.shadowRoot) ? child.childNodes.length : child.shadowRoot.childNodes.length;
> ```
> 
> eruda/src/Elements/Elements.js [Line 291](https://github.com/liriliri/eruda/blob/master/src/Elements/Elements.js#L291)
> 
> ```js
> // From
> ret.children = formatChildNodes(el.childNodes)
> // To
> ret.children = formatChildNodes((!el.shadowRoot) ? el.childNodes : el.shadowRoot.childNodes);
> ```

I've created a pull request with eruda/shadow-dom, view it [here](https://github.com/liriliri/eruda-dom/pull/3)

**Comment by surunzi** [comment]
Use version 3.4.0

**Comment by MasterInQuestion** [comment]
Up: [ https://github.com/liriliri/eruda/commit/ddac0c93533de47d0fc200f8dc3833c3b03bba0f#diff-fbf7686bfc0e147df2628dbfba74a8f468849f638699eff41bd739041cd215fdR312](https://github.com/liriliri/eruda/commit/ddac0c93533de47d0fc200f8dc3833c3b03bba0f#diff-fbf7686bfc0e147df2628dbfba74a8f468849f638699eff41bd739041cd215fdR312)

    Unsure about the exact implementation.
    But my implementation here may worth reference:
    [ https://github.com/MasterInQuestion/talk/discussions/11#discussioncomment-10726273](https://github.com/MasterInQuestion/talk/discussions/11#discussioncomment-10726273)
    .
    The "rs" function deals with Shadow DOM, reliably.

    Several caveats:
    |1| "shadowRoot" may be recursive.
    |2| Host element of "shadowRoot" may still have other children.

**Comment by tathastu871** [comment]
add feature to copy unique selector for elements including shadow
