### ISSUE TITLE
readme 给出的方法被禁止跨域脚本被干掉了

### ISSUE THREAD

**Issue by Sodium-Aluminate** [liriliri/eruda#161]
根据中文 readme，在其他页面地址栏输入
`javascript:(function () { var script = document.createElement('script'); script.src="//cdn.jsdelivr.net/npm/eruda"; document.body.appendChild(script); script.onload = function () { eruda.init() } })();`
可加载控制台，但实际上除了在[代码托管页面](https://cdn.jsdelivr.net)之外没有任何域名有效…

~~或许把 readme 里加载 js 的方式换一个邪道方法可能有一些帮助？~~

**Comment by Sodium-Aluminate** [comment]
貌似根据同源策略大部分浏览器都会干掉…

**Comment by surunzi** [comment]
不是同源策略，js 脚本是可以跨域的。你说的应该是 csp，这个无解。
