### ISSUE TITLE
大神，您好！安装eruda遇到困难，向您求教。谢谢！

### ISSUE THREAD

**Issue by liuzhenyilzhy** [liriliri/eruda#163]
大神，您好！
本人菜鸟一只，业余爱好。原意只是想找一款在安卓手机上的浏览器，可以使用开发者工具。
因为有时候身边没有电脑，只有手机，还需要用到手机浏览器的开发者工具。
后来发现eruda是唯一选择。
没有带开发者工具的安卓手机浏览器。
别的调试工具都是远程调试，都需要用电脑。

我的主要需求，用安卓手机chrome浏览器或firefox，打开baidu或sina等网页时，可以打开eruda查看网页的信息，主要是控制台console的信息。

现在安装eruda遇到困难，向您求教。谢谢！
我根据readme，用npm安装。
因为我不是网页开发人员，不知道其他方法怎么用，其他方法貌似要在网页源码中添加代码，我不知道如何在手机上得到sina的源码。
所以我用npm安装试试看。
根据网上找的安装npm方法，我先装了个termux，然后用termux装了nodejs和npm。
在termux中输入npm -v，得到6.14.7。即：
$ npm -v
6.14.7
我想应该是npm安装成功了。

然后我不知道npm install eruda --save这条命令应该在哪里输入？
于是我在termux中输入npm install eruda --save得到：
$ npm install eruda --save
npm WARN saveError ENOENT: no such file or directory, open '/data/data/com.termux/files/home/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/data/data/com.termux/files/home/package.json'
npm WARN home No description
npm WARN home No repository field.
npm WARN home No README data
npm WARN home No license field.

+ eruda@2.4.1
added 1 package from 1 contributor and audited 1 package in 5.571s
found 0 vulnerabilities
我知道我这么搞肯定是错了。

但是就像我想做的：
用安卓手机chrome浏览器或firefox，打开baidu或sina等网页时，可以打开eruda查看网页的信息，主要是控制台console的信息。
我应该怎样操作，可以实现我的目的？
还要装别的东西？要得到比如sina网页的源码，然后加入代码才能用？
谢谢大神！

**Comment by haha370104** [comment]
一般来说呢……这个工具是用来调试自己的代码的

如果一定要求「只用手机」并且希望「调试别的网页」，那你需要搞一些比较麻烦的事情。

参考 charles 这样的代理工具，大概要做的事情是找一个可以劫持手机流量的 app，然后解 https 包，并且在 html 里插入一段 script 代码（有点像运营商的流量劫持，但是区别是你自己劫持自己并且需要处理好 https 的问题）

我没怎么用过安卓不太清楚有没有这样的工具，但多半是没有得需要你自己开发的。
