### ISSUE TITLE
请去掉这个滚动条，经常导致tab点击无效

### ISSUE THREAD

**Issue by gp5251** [liriliri/eruda#170]
请去掉这个滚动条，经常导致tab点击无效。
如有需要我可以提pr：）

![image](https://user-images.githubusercontent.com/995572/100846886-06f1bf80-34ba-11eb-961d-7f8a3950ab05.png)

**Comment by xxj7527** [comment]
eruda.util.evalCss('.eruda-dev-tools .eruda-tools .eruda-network .eruda-requests li { overflow-x: hidden;}')

试试(https://github.com/liriliri/eruda/issues/73)

**Comment by surunzi** [comment]
Fixed in the latest version.
