### ISSUE TITLE
Android4.4.x兼容

### ISSUE THREAD

**Issue by iulo** [liriliri/eruda#171]
Hi，目前最新的2.4.1 不能兼容到Android4.4.x（chrome30），我看了下报错，应该是因为Map对象没有polyfill，请兼容下

在build脚本中，我看到[babel-preset-env](https://github.com/liriliri/eruda/blob/master/build/webpack.base.js#L57)中没有指定browserlist相关配置，这样恐怕每次构建都是不稳定的

**Comment by surunzi** [comment]
Map polyfill 已加，测试 Android 5.0 可以正常运行。
