### ISSUE TITLE
Simply doesn't load in certain conditions.

### ISSUE THREAD

**Issue by ghost** [liriliri/eruda#173]
So, I have a school Chromebook that I've tried to see it on with the bookmarklet, and it simply does not work in these conditions, along with it using jsDelivr:
 

- **If you have any type of web protection like ZScaler
- If you use any thing besides [this bookmarklet](javascript:(function () { var script = document.createElement('script'); script.src="https://eruda.liriliri.io/eruda.min.js"; document.body.appendChild(script); script.onload = function () { eruda.init() } })();)**
And even if you do that, alas it my not work.An example of the pages that it works on are pages that use HTML to create page elements (not roblox witch uses JS to create elements an mojardy of the time).

I have no idea why it's caused, but I will investigate further!

**Comment by Solo67500** [comment]
![]()
