### ISSUE TITLE
There is some wrong in README

### ISSUE THREAD

**Issue by MuYunyun** [liriliri/eruda#181]
![image](https://user-images.githubusercontent.com/19354791/106455519-44c59100-64c7-11eb-8bb9-324703b0f1c4.png)

There is no effect when I use like this:

```js
eruda.init({
    tool: ['resource]
 });
```

Instead I should use like this:

```js
eruda.init({
    tool: ['resources]
 });
```

Why not instead resource with resources?

**Comment by surunzi** [comment]
Fixed the docs, it should be `resources`.
