### ISSUE TITLE
[Feature Request] Console 只有, All, Info, Warning, Error 的 filter, 期望再添加一个 Log 的 filter

### ISSUE THREAD

**Issue by yyyanghj** [liriliri/eruda#182]
用了一些第三方包, 里面有大量的 info 级别的无用 log。eruda 选中 All 的 filiter 时, 会显示所有 log, 使项目里普通 log 和第三方info log 混杂， 非常影响调试。联系第三方包作者答复时暂时没办法加个开关控制。

**Comment by surunzi** [comment]
这里以前有，后面去除了。有特殊过滤需求的可以调用相关接口：`eruda.get('console').filter('log')`

**Comment by yyyang1996** [comment]
> 这里以前有，后面去除了。有特殊过滤需求的可以调用相关接口：`eruda.get('console').filter('log')`
我们是在构建时判断环境变量来注入 eruda,  之前尝试过调用 eruda.get('console').filter('log'), 但是我们只会在 eruda.init 之后调用一次, 不会在业务代码里调用。
这样初始可以过滤出 log, 但是当点击了 Info, Error 之后, 又恢复原样了, 这对于我们来说变成了一次性的过滤。我们没办法来回在 log 和 error 之间切换。

**Comment by surunzi** [comment]
这里看了下，chrome 那边选择 info 类别时是会包括 console.log 跟 console.info 的日志，eruda 后边会对齐下。

**Comment by surunzi** [comment]
console 这边整个正在用 ts 重构，可能不会那么快。。

**Comment by surunzi** [comment]
新版过滤跟日志级别区分开了，可以使用 filter 过滤不用的选项，点击 Info, Error 不会影响 Filter。
```javascript
eruda.get('console').filter(function (log) {return false})
```
