### ISSUE TITLE
Please read

### ISSUE THREAD

**Issue by open-codebranch** [liriliri/eruda#185]
In order to try it for different sites, execute the script below on browser address bar.

I am not sure what you said here. Please show how to use this tool.

**Comment by 14725** [comment]
It means: copy them, then paste it into browser's address bar. Finally press enter.

 If everything is OK, then the script will load eruda and show it. 

( However, it may not work due to the limit of the mobile browser. If this happens, please ask for a scripting extension for help.  )

**Comment by mullcom** [comment]
Did try it on chrome beta. But I get redirected to google serche.

Open site and depot all text in adressbar then place 

​javascript:​(​function​ ​(​)​ ​{​ ​var​ ​script​ ​=​ ​document​.​createElement​(​'script'​)​;​ ​script​.​src​=​"//cdn.jsdelivr.net/npm/eruda"​;​ ​document​.​body​.​appendChild​(​script​)​;​ ​script​.​onload​ ​=​ ​function​ ​(​)​ ​{​ ​eruda​.​init​(​)​ ​}​ ​}​)​(​)​;

**Comment by 14725** [comment]
...
I do not use chrome beta, sorry.
There are invisible space in your text, making the browser confused. 
It may help if you copy it from https://github.com/liriliri/eruda/edit/master/README.md. 

In addition, if you use a mobile, the "text" is likely to fail anyway :-)

**Comment by ProphetZarquon** [comment]
Doesn't work for me either...  

https://eruda.liriliri.io/ has a console that comes up, but `javascript:(function () { var script = document.createElement('script'); script.src="//cdn.jsdelivr.net/npm/eruda"; document.body.appendChild(script); script.onload = function () { eruda.init() } })();` does nothing (nothing visible, at least).  😢 

Chrome 91.0.4472.120 
Android 7.1.1; 9024W Build/NMF26F

**Comment by algorythmic** [comment]
Chrome mobile will remove `javascript:` from the start of pasted text. You need to go to the start of the URL in the address bar and add it back.
Alternatively, bookmark the `javascript:` URL and invoke the bookmark by typing the bookmark's name.

**Comment by Oreeeee** [comment]
This should be included in the README
