### ISSUE TITLE
please support inspecting shadowDOM

### ISSUE THREAD

**Issue by mimiza** [liriliri/eruda#188]
Hello there and first of all thank you the people behind this tool so much for such an amazing hard work. I love this tool. It helps me unstick myself from my toxic desk and laptop. Yayyy

Hey but it doesn't let me view shadowDOM inside Custom Elements. Nowadays native web components are everywhere buddies.

Would you guys please support inspecting shadowDOM pleaseeee?

Looking forward to seeing this tool thrives.

Best regards,
Shan.

**Comment by ljcucc** [comment]
Yeah, it'll be nice to having this feature, I'm having painful to trying modify my website which built completely with web components.

**Comment by surunzi** [comment]
Duplicate #158
