### ISSUE TITLE
用npm install eruda 下载的是1.1.3版本 

### ISSUE THREAD

**Issue by lmh2072005** [liriliri/eruda#19]
用npm install eruda 下载的是1.1.3版本 ，看你demo里用的是 eruda v1.2.0版本

**Comment by surunzi** [comment]
Demo会一直保持跟GitHub上的最新代码同步，包括自上个版本（v1.1.3）发布后所做的修复改进，下一个准备发布的版本是v1.2.0。

PS：请不要使用Demo里的版本，因为更新比较频繁，bug也可能较多。
