### ISSUE TITLE
It does not seem to work on GitHub?

### ISSUE THREAD

**Issue by Querela** [liriliri/eruda#190]
Tested on latest Chrome Browser in Android 10.
Amazon, Stackoverflow and some other websites worked. (Sometimes the DevTools icon was out of view on the right, scaled down or hidden behind the readmode bottom banner, but not sure for GitHub.)
Also doesn't work for Hackernews/ycombinator. In a comment, 'CSP' was mentioned.

(Also no debug or error messages using https://paul.kinlan.me/quick-console-bookmarklet-for-desktop-and-mobile/ console. Maybe wrap initialization in try-catch?)

**Comment by Querela** [comment]
Otherwise, really nice. Great work and I'm happy I stumbled over it by chance else I wouldn't even know about it.

**Comment by Querela** [comment]
CSP: Content Security Policy
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

Maybe (if possible) add detection for CSP in Bookmarklet?

**Comment by leohku** [comment]
Hey! Late post but I've created a script here: https://github.com/leohku/andure to get Eruda working in Github and other websites where Content Security Policy is set. Feel free to follow the installation steps and check it out!
