### ISSUE TITLE
Init with (ShadowDom = false) Failing if previously (ShadowDom was = true)

### ISSUE THREAD

**Issue by SparshaDhar** [liriliri/eruda#195]
Hi, I want to first init eruda with (ShadowDom = true).
`Step 1. >` `eruda.init();`
This is to detect any failure before Cordova App has Loaded completely.

After loading complete I wanted to destroy the previous Eruda Object.
`Step 2. >` `eruda.destroy();`

Then for all users using the app, I wanted to embed it into a container.
`Step 3. >` `eruda.init({useShadowDom: false,});`

Then after Step 3, everything gets messed up.

Thanks.

**Comment by 125441** [comment]
👍

**Comment by surunzi** [comment]
It should be fixed in the latest version.
