### ISSUE TITLE
Persistent User-Defined Snippets?

### ISSUE THREAD

**Issue by RebBlumstein** [liriliri/eruda#196]
In devtools on chrome desktop, there is the ability to write and save snippets, and these snippets will persist after restarting chrome. There are built-in "snippets" in Eruda, but I don't see how to add my own in a similar way. This makes the "snippets" section a bit weird. Is there a way to save my custom snippets on my device?

**Comment by surunzi** [comment]
https://github.com/liriliri/eruda/blob/master/doc/TOOL_API.md#snippets

```javascript
eruda.get('snippets').add('Test', function () {console.log('test')}, 'description')
```
