### ISSUE TITLE
Request: New Tab Page / Open URL

### ISSUE THREAD

**Issue by RebBlumstein** [liriliri/eruda#197]
Currently, you have to run a javascript line in the address bar on a given page to open the developer tools.

It would be very helpful if there was a way to open https://eruda.liriliri.io/ and open another page "inside" it. The page would (for example) open inside a child element that mimics a normal browser tab, so that refreshing the page or clicking a link wouldn't remove the developer tools interface.

**Comment by surunzi** [comment]
It is not possible because you can't inject script into the page from another domain.
