### ISSUE TITLE
微信浏览器默认初始化面板数量有问题

### ISSUE THREAD

**Issue by DeepenLau** [liriliri/eruda#20]
``` js
  try {
    require('eruda').init()
  } catch (e) {
    alert(e)
  }
```
alert 出来信息是 TypeError: str.slice is not a function. (In 'str.slice(0, len'), 'str.slice' is undefined)

系统：iOS 9.3.5 
微信：6.5.5（UIwebview）

<img width="455" alt="qq20170303-182546 2x" src="https://cloud.githubusercontent.com/assets/14030995/23547624/d724c760-003e-11e7-9c1e-ba734aa45023.png">

<img width="449" alt="qq20170303-183410 2x" src="https://cloud.githubusercontent.com/assets/14030995/23547949/3145f56a-0040-11e7-8bfe-471fcd19dcb0.png">

<img width="442" alt="qq20170303-183451 2x" src="https://cloud.githubusercontent.com/assets/14030995/23547975/55beed52-0040-11e7-80a4-5f3056f53d86.png">

**Comment by surunzi** [comment]
面板初始化有问题具体是哪个面板？

**Comment by surunzi** [comment]
init的时候传入tool参数禁用下resources面板试下：['console', 'network'...]

**Comment by DeepenLau** [comment]
``` js
    try {
      require('eruda').init({
        tool:['console', 'elements', 'network', 'sources', 'info', 'snippets', 'features']
      })
    } catch (e) {
      alert(e)
    }
```
确实禁用掉 resources 就正常了

感谢~

**Comment by surunzi** [comment]
目测获取localStorage或sessionStorage的值时出错了，可以的话能否在console里贴下下面的代码看结果是什么吗？

```javascript
JSON.parse(JSON.stringify(localStorage));
JSON.parse(JSON.stringify(sessionStorage));
```

**Comment by DeepenLau** [comment]
<img width="446" alt="qq20170303-203325 2x" src="https://cloud.githubusercontent.com/assets/14030995/23551411/605cac34-0051-11e7-8416-d0a78efa246f.png">

<img width="448" alt="qq20170303-203420 2x" src="https://cloud.githubusercontent.com/assets/14030995/23551414/699607fa-0051-11e7-89e8-7dca1291fbf1.png">

图传了好几次才成功，
上面是 ls 的，下面的是 ss 的

**Comment by surunzi** [comment]
奇怪，没看出什么问题，我做下保护试试有没有效。这里传文件不方便，可以的话加下Q群：595858210

**Comment by surunzi** [comment]
localStorage.constructor被object赋值导致字符串操作时出现错误，执行前检查下类型合法性即可。

**Comment by qinxianzong** [comment]
学习了
