### ISSUE TITLE
Eruda Memory & Plugin Code

### ISSUE THREAD

**Issue by ghost** [liriliri/eruda#200]
Hi
I do not understand what «eruda memory» is for and what it does ?!
Please add more details and documents
Is it related to localStorage?
&
The theme of the «plugin code» section is not interchangeable!
Requires dark or night mode
Thanks to the eruda development team
Good Luck

**Comment by SparshaDhar** [comment]
Memory should refer to Physical Memory used or the RAM used by that tab/page.
&
Your second question is regarding _eruda-code_ on Github. So maybe you need to report that [here](https://github.com/liriliri/eruda-code/issues).

**Comment by bittnitt** [comment]
> Memory should refer to Physical Memory used or the RAM used by that tab/page.
> &
> Your second question is regarding _eruda-code_ on Github. So maybe you need to report that [here](https://github.com/liriliri/eruda-code/issues).

Thanks, I will definitely create new issues on the memory and code page
I'm still not sure what memory is for!
The chart appears and fills up to 10MB !!
I think it might test the maximum amount that can be stored in Local Storage

**Comment by SparshaDhar** [comment]
Nope memory refers to the amount of Physical Memory or amount of RAM that is being used by your Device to show that Page.

Your Task Manager has a similar Memory Chart, which shows the amount of memory bieng used by all programs and processes, etc. currently running on your computer.
![image](https://user-images.githubusercontent.com/42723600/121901910-776c7980-cd44-11eb-89cb-13bbe41f851e.png)

**Comment by surunzi** [comment]
It shows `performance.memory.usedJSHeapSize`.
