### ISSUE TITLE
能够支持响应数据自动转码吗

### ISSUE THREAD

**Issue by zyzweb** [liriliri/eruda#201]
![image](https://user-images.githubusercontent.com/41266834/122531855-7ee89700-d052-11eb-8b56-c3cfe7c5220d.png)
![image](https://user-images.githubusercontent.com/41266834/122531892-8871ff00-d052-11eb-928e-2d7e629aa714.png)
chrome network可以自动转码,希望大佬能增加一下,万分感谢!

**Comment by zyzweb** [comment]
上下2张图是同一次请求,eruda是展示原始的数据,没有进行转换

**Comment by surunzi** [comment]
最新版本返回字符串为 json 格式的话可以点击结构化查看。
