### ISSUE TITLE
Eruda not working for opera android browser

### ISSUE THREAD

**Issue by F36** [liriliri/eruda#205]
pasting the code on opera's the address bar just searches it as a keyword also I tried the bookmark method it dose nothing

**Comment by ROWEND36** [comment]
Ensure you've removed all the spaces in the text. Add 'void(0);' suffix.

javascript:(function(){var script=document.createElement('script');script.src="//cdn.jsdelivr.net/npm/eruda";document.body.appendChild(script);script.onload=function(){eruda.init()}})();void(0);

**Comment by gikdev** [comment]
I tried tried that but not working

**Comment by surunzi** [comment]
Not an eruda issue.
