### ISSUE TITLE
How to run in facebook 

### ISSUE THREAD

**Issue by ntkhang03** [liriliri/eruda#210]
i tried to enable it on facebook website but devtools button is not displayed. Pls help me

**Comment by X7md** [comment]
you can't do that

![image](https://user-images.githubusercontent.com/54203033/130811351-9451a8e6-da49-43f6-9e6a-2d413ec2803e.png)

facebook not allow you.


try use **(kiwi.next)** browser it's have an real chromium devtools   

https://github.com/kiwibrowser/src.next

![image](https://github.com/X7md/static/blob/main/Screenshot_20210718-232734_Kiwi%20Browser%20(Next).jpg?raw=true)

**Comment by leohku** [comment]
Hey! Late post but I've created a script here: https://github.com/leohku/andure to get Eruda working in Facebook and other websites where Content Security Policy is set. Feel free to follow the installation steps and check it out!

**Comment by X7md** [comment]
> Hey! Late post but I've created a script here: https://github.com/leohku/andure to get Eruda working in Facebook and other websites where Content Security Policy is set. Feel free to follow the installation steps and check it out!

Nice 💝
