### ISSUE TITLE
does not work on pages which are locally hosted on device?

### ISSUE THREAD

**Issue by devalllex** [liriliri/eruda#238]
i opened a page from my storage directly on browser after applying the eruda it does not show up but on other pages it works fine

**Comment by ibnsamy96** [comment]
I think it's a security feature created by your browser as you can't make any requests from an html file that is located locally and opened using "file://" so you can't download the eruda js file. You need to open it through a local webserver, You may use [Termux](https://termux.com/) combined with [Node](https://nodejs.org/en/) and [Live-Server package](https://www.npmjs.com/package/live-server) to open your page with a local webserver.

**Comment by devalllex** [comment]
> I think it's a security feature created by your browser as you can't make any requests from an html file that is located locally and opened using "file://" so you can't download the eruda js file. You need to open it through a local webserver, You may use [Termux](https://termux.com/) combined with [Node](https://nodejs.org/en/) and [Live-Server package](https://www.npmjs.com/package/live-server) to open your page with a local webserver.

thnaks for the feedback
