### ISSUE TITLE
Monitoring Fetch Requests

### ISSUE THREAD

**Issue by omarchehab98** [liriliri/eruda#24]
`window.fetch` is currently not being monitored by Eruda.

Unlike XHR requests, fetch can be monitored through an event listener, `window.addEventListener('fetch', function (request) { ... })`.

**Comment by surunzi** [comment]
I just noticed fetch is supported in safari for ios 10.3 recently. Definitely going to support it in eruda later.

**Comment by surunzi** [comment]
Supported in v1.4.0
