### ISSUE TITLE
support dynamic import

### ISSUE THREAD

**Issue by luckymore** [liriliri/eruda#246]
```js
if (env !== 'online') {  
  import('eruda').then(eruda=> {
    eruda.init()
  })
}
```
this way is not work

**Comment by lasoforo** [comment]
> ```js
> 
> if (env !== 'online') {  
> 
>   import('eruda').then(eruda=> {
> 
>     eruda.init()
> 
>   })
> 
> }
> 
> ```
> 
> this way is not work

**Comment by lostncg** [comment]
@lasoforo @luckymore I guess u used the dynamic import wrongly.
The dynamic import return a "file" object, your script content is park under `default` property
Hence, the expected source code should be:
```js
import('eruda').then(eruda=> {
    console.log(erufa) // print it out to understand the truth
    eruda.default.init()
})
```

**Comment by luckymore** [comment]
@lostncg my mistake... thx and close
