### ISSUE TITLE
uniapp中可以使用吗？没有div的话

### ISSUE THREAD

**Issue by bweib** [liriliri/eruda#255]

**Comment by Xavier9896** [comment]
uni-app里面不行啊，编译为安卓和ios，页面打开直接啥都没了，一片空白

**Comment by Xavier9896** [comment]
> 

h5里面是正常的，就只有编译到安卓和ios有问题

**Comment by Clown112** [comment]
我的就是H5使用的，APP端的话好像没有使用过




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月1日(星期一) 上午10:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liriliri/eruda] uniapp中可以使用吗？没有div的话 (Issue #255)





   
h5里面是正常的，就只有编译到安卓和ios有问题

**Comment by bweib** [comment]
您好！您的邮件我已收到，我会尽快查看的，谢谢！

**Comment by surunzi** [comment]
仅支持在浏览器环境中使用。

**Comment by XiaoHui-Top** [comment]
请问有解决吗

**Comment by bweib** [comment]
您好！您的邮件我已收到，我会尽快查看的，谢谢！

**Comment by xzq152** [comment]
我也想在APP端使用有什么好的办法吗？

**Comment by bweib** [comment]
您好！您的邮件我已收到，我会尽快查看的，谢谢！
