### ISSUE TITLE
How should security vulnerabilities be reported? (xss)

### ISSUE THREAD

**Issue by hello-smile6** [liriliri/eruda#263]
I found a vulnerability, and need to know how to report it.

**Comment by 14725** [comment]
I don't think eruda was maintained. So why not publish the vulnerability in public so that a fork version could get it fixed? 

@liriliri Come out and prove I'm wrong.

**Comment by surunzi** [comment]
You can just email me: surunzi@foxmail.com
It's still being maintianed, and I'm currently rewriting some of its components in another [repository](https://github.com/liriliri/luna), so you don't see many updates here.

**Comment by hello-smile6** [comment]
> You can just email me: [surunzi@foxmail.com](mailto:surunzi@foxmail.com) It's still being maintianed, and I'm currently rewriting some of its components in another [repository](https://github.com/liriliri/luna), so you don't see many updates here.

Sounds good! I'll email you
