### ISSUE TITLE
2.5.0 is hiding all dom elements

### ISSUE THREAD

**Issue by mithrendal** [liriliri/eruda#269]
I am using eruda in 

https://vAmigaWeb.github.io 

eruda can be enabled in settings->load logging console

with 2.4.1 everthing was smooth and working nicely... now with 2.5.0 upon eruda.init() it brings up eruda but at the same time 😳 all controls of the vAmigaWeb app are hidden... resulting in a gray empty space ... despite this the app is running and the drive stepper motor of the Amiga produces the floppy disk motor sound... upon eruda.destroy() the Amiga web app  becomes visible again ...

I fixed it by addressing the previous eruda version with the URL suffix @2.4.1

**Comment by surunzi** [comment]
2.5.0 starts to use canvas for highlighting dom elements, and its id is the same as the one you are using...

**Comment by surunzi** [comment]
Use version 2.6.0 and see if it is fixed.

**Comment by mithrendal** [comment]
2.6.0 fixes the issue ... works like 2.4.1 i.e. does not hide anything .

Thank you ! ❤️
