### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by Alcatraz323** [liriliri/eruda#27]
https
localhost server cant retrieve source

**Comment by surunzi** [comment]
Do you mean the sources panel not showing the html code?

**Comment by Alcatraz323** [comment]
For local server just the source panel,for https the toggle wont show

RedHoodSu <notifications@github.com>于2017年5月14日周日 09:35写道：

**Comment by surunzi** [comment]
I tested it in localhost with both http and https. And it all works fine. Can you run it in desktop browsers to check if any error occurs while loading and initializing the script?
