### ISSUE TITLE
加载相对路径的luna-dom-highlighter.css.map文件

### ISSUE THREAD

**Issue by faxintan** [liriliri/eruda#272]
加载相对路径的luna-dom-highlighter.css.map文件，到时Server层处理了无用的请求

**Comment by Gmskjunior** [comment]
> 加载相对路径的luna-dom-highlighter.css.map文件，到时Server层处理了无用的请求

Hgggggggggggggggg

**Comment by surunzi** [comment]
最新版应该不会加载了
