### ISSUE TITLE
bad classes in eruda.

### ISSUE THREAD

**Issue by dartess** [liriliri/eruda#28]
Please, if possible, delete classes that do not begin with "eruda-". I met a problem with the class "filter". My code uses this class to define a component in DOM. I'm getting errors in the console. Thank you in advance.

**Comment by surunzi** [comment]
Download the latest script from http://eruda.liriliri.io/eruda.min.js and see if it's fixed.

**Comment by dartess** [comment]
thanks, fixed!

**Comment by dartess** [comment]
...but I can not use http, since our site is https. https://cdnjs.cloudflare.com/ajax/libs/eruda/1.2.3/eruda.js does not include class changes.
Can you advise something? In addition to downloading the file.

**Comment by dartess** [comment]
If possible, can you upgrade to CDN? I can not use the script on http.

**Comment by surunzi** [comment]
Then you'll have to wait for the next version to be released. I'll try to get it done within the week.

**Comment by dartess** [comment]
Very cool, thanks
