### ISSUE TITLE
eruda.js tries to access nodeType property of Proxy instances when logged to console 

### ISSUE THREAD

**Issue by Hit-And-Run-5677** [liriliri/eruda#286]
I am creating a Proxy instance and printing it to the console like this-
```javascript
const x = new Proxy({}, {
  get (target, prop, ctx) {
    console.log(prop)
    
    return Reflect.get(target, prop, ctx)
  }
})

console.log(x)
```

When this code is run, the output printed to the console is like this-
```
Object {  }
Symbol(Symbol.toStringTag)
nodeType
Symbol(Symbol.toStringTag)
constructor
Symbol(Symbol.toStringTag)
```

I understand that for eruda it might be necessary to access properties like Symbol.toStringTag or constructor for logging a Proxy instance to console but it is trying to access the **"nodeType"** property of Proxy instances, which causes a problem for me in writing code. 

As you know **"nodeType"** is not a property of prototype of any Proxy or any Object but of HTMLElement instance, so I request you to fix this bug.

**Comment by surunzi** [comment]
It uses nodeType property to check whether object is an HTMLElement. If true, eruda logs out html string instead of  regular object view.

**Comment by Hit-And-Run-5677** [comment]
Ok
