### ISSUE TITLE
[Bug] "luna-tab-item"s don't display in Firefox

### ISSUE THREAD

**Issue by MasterInQuestion** [liriliri/eruda#293]
Tested Firefox 108.
    Regression introduced by Eruda v2.7.3.

    Likely related: #236

**Comment by surunzi** [comment]
Use version 2.7.4 and see if it is fixed.

**Comment by MasterInQuestion** [comment]
Firefox "document.body" is null error:
    I believe which shouldn't occur in current Firefox. [ [https://caniuse.com/mdn-api_document_body](https://caniuse.com/mdn-api_document_body) ]

    Would you mind indicating the details causing the issue?

**Comment by surunzi** [comment]
Not a firefox bug. The root cause is that firebox does not support custom scrollbar. In that case, luna-tab will try to access document.body before it is ready.

**Comment by MasterInQuestion** [comment]
Thanks.
    Would you mind indicating the change that resolves the issue?

**Comment by surunzi** [comment]
https://github.com/liriliri/luna/commit/4c9eac2cb1cc09cf9230f42be5e5929873c759ac

**Comment by MasterInQuestion** [comment]
Would you mind giving more debug info on how you located the problem?

    The diff you linked indicated the cause was "document.body"?
    Do you mean that in Firefox "document.body" would return null under certain conditions?
