### ISSUE TITLE
The mobile app

### ISSUE THREAD

**Issue by CalSch** [liriliri/eruda#296]
When I search up "eruda" on Google, the second result is a Play Store app. I installed it and it was just a web browser with eruda auto loaded. When I looked at the "about eruda" section it does not reference this repository anywhere! There is no reference of liriliri and they seem to be taking full credit of it.  
I love the eruda project, and I just wanted to let you know in case you weren't okay with this.

**Comment by surunzi** [comment]
Thanks for letting me know, currently I'm ok with it.

**Comment by surunzi** [comment]
I just wrote [one](https://github.com/liriliri/eruda-android/) myself:)
