### ISSUE TITLE
Bypass font-src CSP

### ISSUE THREAD

**Issue by JingMatrix** [liriliri/eruda#297]
Hello, do you have any idea to by pass github's font-src CSP?

When I load erdua for `github.com`, I cannot see icons since the font-family data url is blocked.

**Comment by JingMatrix** [comment]
Now I solved this problem in my application [ChromeXt](https://github.com/JingMatrix/ChromeXt) by interpolating unicodes with eruda-icon font,
see https://github.com/JingMatrix/ChromeXt/blob/ce0ac806f297ac48c76395614f2858733dd069ce/app/src/main/java/org/matrix/chromext/script/LocalScripts.kt#L208-L288  for details.

It will be good if you can adapt similar approche for this problem.

**Comment by surunzi** [comment]
No, I'll stick to icon font, you can't find all icons you need in unicode chars.
