### ISSUE TITLE
在微信浏览器中的一些问题

### ISSUE THREAD

**Issue by nanedo** [liriliri/eruda#3]
这真是一个很棒的工具~~

使用的是小米5测试的。

首先是一些样式问题：
1.html根节点的font-size会影响elements版块的“节点”字体大小，不方便浏览，建议隔离页面的样式影响，同样受影响的有snippets、sources版块；
2.resource版块的属性跟值同一行展示，当属性名称很长时，值会被挤成竖向显示，导致左边出现大块空白；

其它反馈：
当访问的是纯静态的html文件时，微信里使用snippets的刷新页面功能基本没用，囧~~（是不是可以通过ajax获取内容来刷新页面。。。）

最后，感谢提供这么一个好工具~

**Comment by surunzi** [comment]
感谢反馈:) 相关问题已列入计划，会在本周之内修复完善。

**Comment by surunzi** [comment]
@nanedo 0.5.0版已修复，使用方式有些改变，需要手工调用`eruda.init()`进行初始化。

**Comment by nanedo** [comment]
nice!
