### ISSUE TITLE
Does not open when clicked in a physical mouse

### ISSUE THREAD

**Issue by qxb3** [liriliri/eruda#302]
Hi! i don't know why but when i click the icon to open eruda it doesn't work

the clicks are registering but it doesnt't open

**Comment by surunzi** [comment]
Unable to reproduce, try version 2.8.3 and see if it is ok because I've refactored the code related with entry button in version 2.9.x.

**Comment by surunzi** [comment]
Try 2.11.0 and see if it is fixed.

**Comment by qxb3** [comment]
https://user-images.githubusercontent.com/59109346/213472093-82762896-ccf5-431f-afdd-c2c5c19ae8b4.mp4

**Comment by surunzi** [comment]
So you're using a mouse on a phone?

**Comment by qxb3** [comment]
yes

**Comment by surunzi** [comment]
Try deleting ontouchstart to force eruda to use mouse events.
```html
<script>delete window.ontouchstart</script>
<script src="//cdn.jsdelivr.net/npm/eruda"></script>
<script>eruda.init();</script>
```

**Comment by qxb3** [comment]
still not working

**Comment by qxb3** [comment]
no wait, it is working!
