### ISSUE TITLE
Vue3 使用 eruda self is not defined 

### ISSUE THREAD

**Issue by m-xlsea** [liriliri/eruda#303]
nuxt3+Vue3使用eruda报错self is not defined 
版本：2.11.0
![image](https://user-images.githubusercontent.com/53625177/215237588-fbb564d2-503d-4b07-8f9f-5c735d58265b.png)

**Comment by surunzi** [comment]
不要在服务端（node 环境）引入 eruda 。

**Comment by m-xlsea** [comment]
> 不要在服务端（节点环境）引入eruda。

万分感谢，已解决
![image](https://user-images.githubusercontent.com/53625177/215239961-e8be9931-b416-4095-8e07-58b2f51a3668.png)
