### ISSUE TITLE
与 lazysizes 一起使用时出现了个问题

### ISSUE THREAD

**Issue by keywindy** [liriliri/eruda#31]
![screenshot from 2017-08-17 11-31-17](https://user-images.githubusercontent.com/8074705/29398654-6c597bb8-8358-11e7-87f9-9987860788e4.png)
![screenshot from 2017-08-17 11-30-49](https://user-images.githubusercontent.com/8074705/29398671-7c5d5a98-8358-11e7-84f0-13e7efa53a36.png)

参考上面两个图
lazysizes 中执行 addEventListener('resize', debouncedUpdateElementsSizes); 时
在 eruda 中的 overrideEventTarget 里 this 即 addEvent 的 target / el 为 undefined
导致 lazysizes 无法正常执行

我没有整明白这里面到底是怎么引起的, 是否有需要将 addEvent 的 el 参数默认为 window ???

**Comment by surunzi** [comment]
修复了，需要等下个版本发布，急的话可以先在设置面板将“Catch Event Listeners”选项关闭。

**Comment by surunzi** [comment]
1.2.5版已发布，可以下载看是否已修复该问题
