### ISSUE TITLE
问题：移动端使用rem的情况下，面板太小的解决方案

### ISSUE THREAD

**Issue by jzlxiaohei** [liriliri/eruda#32]
现在移动端，为了适配大小问题，使用rem的解决方案。 具体见 https://github.com/amfe/lib-flexible

三倍屏下，会先把页面的 scale 设成 1/3, 这种情况下，调试面板就太小了。

我们自己写css时，会通过postcss 把px 转成rem。

这个虽然不是库需要考虑的，但是移动端rem还是挺常用，这种情况的确太影响使用了。

**Comment by surunzi** [comment]
试了下，通过动态修改样式的数值是个可行的方案，但由于有部分数值hardcode在了js中没办法只通过修改样式文件完美处理，下个版本我看能不能将那部分代码移除掉。

**Comment by jzlxiaohei** [comment]
恩，在不影响不用rem的情况下，希望尽量考虑下。非常感谢

**Comment by AkiraSun** [comment]
rem布局下试了楼主这个方法的确还是字体的大小不能更改，按钮位置也会发生些变化，感觉移动端这个适配的必要性还是非常大哈

**Comment by surunzi** [comment]
这样做按钮移位是已知问题，不过ios下替换了`eruda.util.evalCss`也没法改变？可否贴个Demo链接？

**Comment by AkiraSun** [comment]
http://www.jianshu.com/p/985d26b40199
我使用的是这种高清rem布局，所以会导致布局不准确
按钮可以修改，eruda.util.evalCss下的字体选项略多。。不知从何下手

**Comment by surunzi** [comment]
@AkiraSun 不太明白你说的情况是什么，我自己用上边的代码在android跟ios下基本是可以正常使用的。

PS: 那个var initialScale = 0.33333是需要自己根据页面当前scale进行调整。

**Comment by AkiraSun** [comment]
@surunzi  可以麻烦贴下eruda.util.evalCss 修改的代码吗

**Comment by tesky0125** [comment]
> 感谢楼主，font-size正则匹配有点小问题，未考虑空格，增加\s*即可，以下未更新后的代码片段

``` javascript
        css = css.replace(/font-size:\s*(\d+)px/g, function($0, $1) {
            return 'font-size:' + (+$1 * scale) + 'px';
        });
```

**Comment by tesky0125** [comment]
另外initialScale = 0.33333; 建议改成
```
var dpr = window.devicePixelRatio || 1;
var initialScale = 1 / dpr;
```

**Comment by surunzi** [comment]
@jzlxiaohei 1.3.0加了autoScale功能，可以试下有没有效果

**Comment by jzlxiaohei** [comment]
我这个验证了下，展示效果很赞。
