### ISSUE TITLE
为什么console控制台打印不出来信息

### ISSUE THREAD

**Issue by lovelyJason** [liriliri/eruda#325]
我是hexo博客，开发模式手机远程调试，还是生产环境上运行eruda， console控制里面都没有信息打印是咋回事

看图， 需要提供什么数据吗？

![image](https://user-images.githubusercontent.com/50656459/234499812-55155009-fef6-4b78-abb7-d42f9a934fcf.png)

这是页面body底部插入的代码

![image](https://user-images.githubusercontent.com/50656459/234499874-9d5083bb-4811-485a-91d9-a2527a2e2dae.png)

**Comment by hanhan9449** [comment]
因为eruda初始化的时候你这个日志已经打印了，没法捕获在执行初始化前的日志
