### ISSUE TITLE
怎么安装到手机端的浏览器中进行使用呢

### ISSUE THREAD

**Issue by Supreme-A** [liriliri/eruda#339]

**Comment by fatso83** [comment]
Wtf

**Comment by Supreme-A** [comment]
？？？平白无故骂人呢排？教养呢？

**Comment by Supreme-A** [comment]
> Wtf

？？？平白无故骂人呢排？教养呢？

**Comment by fatso83** [comment]
LOL. I can see from [the response](https://translate.google.com/?sl=zh-CN&tl=en&text=%E5%B9%B3%E7%99%BD%E6%97%A0%E6%95%85%E9%AA%82%E4%BA%BA%E5%91%A2%E6%8E%92%EF%BC%9F%E6%95%99%E5%85%BB%E5%91%A2%EF%BC%9F&op=translate)  that something got lost in  translationto Chinese. I meant no disrespect: it was just a hint that users of an internationally used issue tracker should stick to English to avoid excluding people.

**Comment by Supreme-A** [comment]
> LOL. I can see from [the response](https://translate.google.com/?sl=zh-CN&tl=en&text=%E5%B9%B3%E7%99%BD%E6%97%A0%E6%95%85%E9%AA%82%E4%BA%BA%E5%91%A2%E6%8E%92%EF%BC%9F%E6%95%99%E5%85%BB%E5%91%A2%EF%BC%9F&op=translate)  that something got lost in  translationto Chinese. I meant no disrespect: it was just a hint that users of an internationally used issue tracker should stick to English to avoid excluding people.

oh,thanks for your tips.

**Comment by Supreme-A** [comment]
> from [`/readme.md`](https://github.com/liriliri/eruda#demo):
> 
> > In order to try it for different sites, execute the script below on browser address bar.
> 
> > ```js
> > javascript:(function () { var script = document.createElement('script'); script.src="//cdn.jsdelivr.net/npm/eruda"; document.body.appendChild(script); script.onload = function () { eruda.init() } })();
> > ```
> 
> also, I've found that it's much easier to make a bookmarklet with that code rather than typing it out every time.
> 
> I hope this helped! (:

Thanks for your help,it's very useful for me.

**Comment by RuralAnemone** [comment]
yeah - another good suggestion is to always read the `readme` file before filing issues (:

glad we could help!

**Comment by eczn** [comment]
https://github.com/whistle-plugins/whistle.inspect
a code-less ways of using eruda: by proxy injection

**Comment by JingMatrix** [comment]
[ChromeXt](https://github.com/JingMatrix/ChromeXt) embeds `eruda` into Chromium based and WebView based browsers. 

Also, some features of `ChromeXt` are added to `eruda`.
