### ISSUE TITLE
Clarify need for concatenation in script injection

### ISSUE THREAD

**Issue by fatso83** [liriliri/eruda#341]
Your README injects a script tag by concatenation of `'<scri'` and `'ipt ...` , but nowhere is it explained why you do so. Is this to avoid some linting rules against hostile script injection? I cannot see any legitimate reason.

**Comment by 14725** [comment]
In fact, the `'<scr' + 'ipt>'` is not nessary; but if we write  `'</script>'` , it would close the \<script\> too early, effectively break the script, which is unexpected.
