### ISSUE TITLE
Feature Require: hope eruda could expose"on" hooks to track show and hide action

### ISSUE THREAD

**Issue by sedationh** [liriliri/eruda#342]
hope eruda could expose"on" hooks to track show and hide action

for example
```tsx
eruda.on("show", () => {})
eruda.on("hide", () => {})
```

I notice some [code](https://github.com/liriliri/eruda/blob/master/src/DevTools/DevTools.js#L32)

```tsx
export default class DevTools extends Emitter {
    ...
```
I understand that the ability is already there, but without the outward exposure and providing the relevant type

I'd be happy to provide a PR :)

**Comment by surunzi** [comment]
`eruda.get()` will return `Devtools` instance if no plugin name is given.
```javascript
eruda.get().on('hide', () => console.log('hide'))
```

**Comment by sedationh** [comment]
i notice this method before
![image](https://github.com/liriliri/eruda/assets/56129212/9ce58dab-f8c8-4b8d-ab0d-9e80e02ee182)

but it lack `on` type
![image](https://github.com/liriliri/eruda/assets/56129212/d4cf6335-cf67-417b-a710-3e925719429a)

**Comment by Khlooddeeb** [comment]
**_
