### ISSUE TITLE
eruda.init() 启用之后，能否控制按钮的停用/启用，或者隐藏/显示？

### ISSUE THREAD

**Issue by dusdong** [liriliri/eruda#35]
比如：
eruda.hide();
eruda.show();

**Comment by surunzi** [comment]
没有这种功能，可以直接`document.getElementById('eruda').style = "display:none"`隐藏，显示同理。有什么场景下需要用到这种功能吗？

**Comment by dusdong** [comment]
运行环境：使用 ionic 开发 Hybrid App
使用场景：在配置页面动态控制 eruda 的停用/启用

我曾经试过在 Ionic 启动时不运行init()，而在配置页增加一个启动按钮进行init()。这种方式在 chrome 调试时能正常启动，但编译成app就不能正常启动了。

所以，我想在 Ionic 启动时 init(); 然后 hide();  ，配置页控制 show() / hide()

另，angular 里面不鼓励直接操作Dom： document.getElementById('eruda').style = "display:none" ，最好能够提供函数。谢谢！

**Comment by surunzi** [comment]
这个工具跟angular又没有什么关系，单纯只是引用罢了，直接操作Dom没什么问题。

**Comment by surunzi** [comment]
后续会考虑加入destroy方法，不过不是简单的显示隐藏，没那么快实现。编译成app后不能正常启动知道是什么原因吗？

**Comment by surunzi** [comment]
下载这个：http://eruda.liriliri.io/eruda.min.js
```javascript
// 显示将hide改为show
eruda.hide(); // 隐藏面板
eruda.entryBtn.hide(); // 隐藏按钮
```

**Comment by surunzi** [comment]
1.3.0已经加入了destroy方法
```javascript
eruda.init();
// 销毁实例
eruda.destroy();
// 重新初始化
eruda.init();
```

**Comment by SoftwareEngineerPalace** [comment]
> 下载这个：http://eruda.liriliri.io/eruda.min.js
> 
> ```js
> // 显示将hide改为show
> eruda.hide(); // 隐藏面板
> eruda.entryBtn.hide(); // 隐藏按钮
> ```
eruda.entryBtn.hide 这个不能生效

**Comment by SoftwareEngineerPalace** [comment]
> 1.3.0已经加入了destroy方法
> 
> ```js
> eruda.init();
> // 销毁实例
> eruda.destroy();
> // 重新初始化
> eruda.init();
> ```

destory 不是隐藏，期望是隐藏

**Comment by smz8023** [comment]
> > 下载这个：http://eruda.liriliri.io/eruda.min.js
> > // 显示将hide改为show
> > eruda.hide(); // 隐藏面板
> > eruda.entryBtn.hide(); // 隐藏按钮
> 
> eruda.entryBtn.hide 这个不能生效

eruda._entryBtn.hide()
