### ISSUE TITLE
Make `network` programmable

### ISSUE THREAD

**Issue by CetinSert** [liriliri/eruda#351]
I want to use `eruda` (only `console` and `network` tools) in a web playground.

![image](https://github.com/liriliri/eruda/assets/27027/0224727f-1bde-42c3-a1fa-7d81822409bf)

---

`vConsole` is currently used in its own `iframe` with console messages sent from the `output` frame.
The isolation ensures we don't have to reload the console on each `<script>` edit → document reload.

`vConsole`'s network panel allows us to programmatically populate requests/responses from a different context with
- [`network.add()`](https://github.com/Tencent/vConsole/blob/dev/doc/plugin_properties_methods.md#vconsolenetworkadd)
- [`network.update()`](https://github.com/Tencent/vConsole/blob/dev/doc/plugin_properties_methods.md#vconsolenetworkupdate)
- [`network.clear()`](https://github.com/Tencent/vConsole/blob/dev/doc/plugin_properties_methods.md#vconsolenetworkclear)

`eruda` only offers
- [`network.clear()`](https://github.com/liriliri/eruda/blob/master/doc/TOOL_API.md#network)

---

Please
1. see https://github.com/Tencent/vConsole/blob/dev/doc/plugin_properties_methods.md#network-panel
2. provide additional methods like `vConsole`'s `network.add()` and `network.update()`

**Comment by surunzi** [comment]
I recommend using [chii](https://github.com/liriliri/chii) instead, which supports rendering in a separate iframe.
Example: https://chii.liriliri.io/test/iframe.html and https://playground.solidjs.com/

**Comment by CetinSert** [comment]
@surunzi – I remember seeing chii. It is too heavy for our purposes (5.1 MB) and stuck at Chrome v97.

**Comment by CetinSert** [comment]
I have discovered the internal `eruda` APIs.
```js
                h.default.trigger("Network.requestWillBeSent", {
                  requestId: e,
                  type: "Fetch",
                  request: n,
                  timestamp: t.time / 1e3
                })
              }
              )),
              n.on("done", (function(e, t) {
                h.default.trigger("Network.responseReceived", {
                  requestId: e,
                  type: "Fetch",
                  response: {
                    status: t.status,
                    headers: t.resHeaders
                  },
                  timestamp: t.time / 1e3
                }),
                p.set(e, t.resTxt),
                h.default.trigger("Network.loadingFinished", {
                  requestId: e,
                  encodedDataLength: t.size,
                  timestamp: t.time / 1e3
                })
```
and will likely just use them and hope for their stabilization in future versions of `eruda`.

**Comment by CetinSert** [comment]
@surunzi – while you are available, I hope you can take a look these about `LunaConsole` https://github.com/liriliri/luna/issues/created_by/cetinsert too! Thank you.

**Comment by surunzi** [comment]
Eruda is using [chobitsu](https://github.com/liriliri/chobitsu) to record network requests and it can be accessed by using `eruda.chobitsu`. Maybe you can modify requests through that.
