### ISSUE TITLE
使用 ionic 开发 Hybrid App，调试及模拟时下正常，编译成ios app不显示图标

### ISSUE THREAD

**Issue by dusdong** [liriliri/eruda#36]
使用 ionic 开发 Hybrid App，调试(ionic serve)及模拟(cordova emulate ios)时正常，编译(cordova build iso)成ios app不显示eruda图标

**Comment by dusdong** [comment]
又可以显示了

**Comment by gianlazz** [comment]
@dusdong https://lazz.tech/blog/chrome-style-dev-tools-on-mobile-with-ionic-eruda/
