### ISSUE TITLE
不支持ES动态导入

### ISSUE THREAD

**Issue by meiseayoung** [liriliri/eruda#368]
```
import('eruda').then(eruda=>{
    eruda.init() //Error
})
```
![image](https://github.com/liriliri/eruda/assets/3381834/4f3b026a-d1da-4c4f-a6e3-5200d7b25bbf)

**Comment by JingMatrix** [comment]
Try this
```js
import("https://cdn.jsdelivr.net/npm/eruda").then(_imports => eruda.init())
```

This is because eruda defines globally an object `window.eruda`.

**Comment by vini123** [comment]
虚幻之物对应着冥冥之路！：《羽》

**Comment by meiseayoung** [comment]
> Try this
> 
> ```js
> import("https://cdn.jsdelivr.net/npm/eruda").then(_imports => eruda.init())
> ```
> 
> This is because eruda defines globally an object `window.eruda`.

Thx. This approach may be feasible, but it is not a formal solution

**Comment by master1lan** [comment]
2024留言，eruda可以支持es动态导入，使用方法如下:
`
import('eruda').then((eruda) => eruda.default.init());
`

**Comment by wenliangzhou** [comment]
> 2024留言，eruda可以支持es动态导入，使用方法如下: `import('eruda').then((eruda) => eruda.default.init());`

不支持呀
