### ISSUE TITLE
动态插入的script报错

### ISSUE THREAD

**Issue by acmilank22** [liriliri/eruda#39]
最近在用一个国产hybrid框架的时候发现，用静态的script标签没问题，但是用动态插入的script，用该框架的模拟器点击右下角的eruda会报错：Cannot set property type of #\<Event\> which has only a getter，chrome上的报错为：Cannot assign to read only property 'type' of object '#\<Event\>'。

```
(function() {
    var consoleScript = document.createElement("script");
    consoleScript.src = "js/eruda.min.js";
    document.head.appendChild(consoleScript);
    consoleScript.onload = function() {
        eruda.init();
    };
})();
```

**Comment by acmilank22** [comment]
找到原因了，不是eruda的问题 ，是那个里面有个js文件有问题。

**Comment by jawQ** [comment]
@acmilank22 请问你的问题是怎么解决得？可以加我qq聊聊？我也遇到类似的问题了。

**Comment by jawQ** [comment]
@acmilank22 请问你的问题是怎么解决得？可以加我qq(757050031)聊聊？我也遇到类似的问题了。

**Comment by acmilank22** [comment]
@jawQ 
在eruda.js里搜索 
```js
o=e.jQuery;
```

然后在这一句后加上
```js
o=0; // o = false; 也可以
```

**Comment by jawQ** [comment]
还能这样，3Q。

**Comment by acmilank22** [comment]
@jawQ 原因大概就是没有e.jQuery 所以把o赋值为false 后面的那句if就不会走了
