### ISSUE TITLE
Icon does not appear on discord 

### ISSUE THREAD

**Issue by FoxGaal** [liriliri/eruda#393]
When I try to use this on discord to get stuff like avatar links I am unable to use this, while logged in and using the homepage of the website

**Comment by UDOY99PRO** [comment]
yeah same problem 
not only in discord but many websites

**Comment by laparda14** [comment]
The problem is that on some websites like discord and gimkit, the eruda icon wont show b/c either the website wont let it be used or the JavaScript code isn’t right.

**Comment by surunzi** [comment]
Because csp is enabled in these websites, use tools like [whistle](https://github.com/avwo/whistle) to bypass it.
