### ISSUE TITLE
请问在sencha touch下如何安装呢？

### ISSUE THREAD

**Issue by chenzm080** [liriliri/eruda#4]
如题，一定要用npm吗？
没办法直接引用js文件吗？

**Comment by surunzi** [comment]
npm只是用于下载js文件，你可以直接把node_modules/eruda/dist目录下的文件拷贝到任何地方，然后直接引入到页面中使用。

**Comment by surunzi** [comment]
@chenzm080 目前暂不考虑npm以外的发布方式，不想用npm的话可以直接下载Demo页的js文件http://liriliri.github.io/eruda/eruda.min.js
