### ISSUE TITLE
Uncaught TypeError: Cannot read property 'navigationStart' of undefined

### ISSUE THREAD

**Issue by xingxing1989** [liriliri/eruda#40]
Uncaught TypeError: Cannot read property 'navigationStart' of undefined
你好请教个问题，在点击network的时候报错，其他可以用

**Comment by surunzi** [comment]
应该是performanceTiming不支持导致，已兼容，下个版本修复，可先在settings面板开启Disable Performance Timing选项。

**Comment by superstarGB** [comment]
谢谢大神

**Comment by superstarGB** [comment]
还有一个问题就是 network中请求只能看Response Headers，我想看ajax 返回的内容在哪看呢？

**Comment by surunzi** [comment]
Response Headers底下应该有内容才对，确定没有？

**Comment by superstarGB** [comment]
目前只显示 contant-type  
 expires  wed,08
cache-control  no-cache

**Comment by surunzi** [comment]
595858210 加Q群截个图看下
