### ISSUE TITLE
Counsel does not show accurate logs

### ISSUE THREAD

**Issue by SaravananRamanathan** [liriliri/eruda#403]
Snippet to recreate the issue:
```
const friends = ['one', 'two', 'three']
const newLength = friends.push('four');
console.log(friends)

friends.unshift('zero')
console.log(friends)

friends[friends.length] = 'five'
console.log(friends)
```
<hr style="background-color: grey;"/>
<p >
for the above snippet, the expected log is (and this is the displayed correct in the Firefox dev counsel):
<img width="529" alt="Screenshot 2023-11-16 at 10 43 01 AM" src="https://github.com/liriliri/eruda/assets/25448502/b18026b5-60db-480a-8656-e7f8df1184c3">
</p>

<p>
Eruda, counsel displays the log as following:
<img width="1050" alt="Screenshot 2023-11-16 at 10 44 27 AM" src="https://github.com/liriliri/eruda/assets/25448502/160d1a5e-a670-4fa7-9acd-19d9188522f9">
</p>

<p>
it seems to show the latest `friends` array value for all 3 logs
</p>

**Comment by Mazedotexe** [comment]
Wow, what an interesting bug! I wonder what causes this.

**Comment by surunzi** [comment]
Turn off "Asynchronous Rendering" in settings and it will be the same.
