### ISSUE TITLE
Is there a function to make Eruda immediately show up?

### ISSUE THREAD

**Issue by Mazedotexe** [liriliri/eruda#408]
`eruda.init()` just creates a devtools button in the bottom-right. Is there an alternative to `eruda.init()` that can make it show up instead of creating a button to do so?

**Comment by CennoxX** [comment]
Use eruda.init(); and then eruda.show();

**Comment by Mazedotexe** [comment]
> Use eruda.init(); and then eruda.show();

Thank you!

**Comment by Dhyfer1** [comment]
> Use eruda.init(); and then eruda.show(); 

In the script code which is this 

```js
javascript:(function () { var script = document.createElement('script'); script.src="//cdn.jsdelivr.net/npm/eruda"; document.body.appendChild(script); script.onload = function () { eruda.init() } })();
```

Where do I put eruda show()?

**Comment by CennoxX** [comment]
Yes, this way.

**Comment by Dhyfer1** [comment]
> Yes, this way.

Okay, thank you very much 😊
