### ISSUE TITLE
在webview内 内核较低的时候 ，打印会有问题

### ISSUE THREAD

**Issue by cjh-store** [liriliri/eruda#431]
![e0c095e50ea39a69be6831904d31d84](https://github.com/liriliri/eruda/assets/88535245/b9399e4b-2c9c-4973-b9a3-2b6e54190315)
在webview内 内核较低的时候 ，打印会有问题
eruda 3.0.1

**Comment by surunzi** [comment]
无法在低版本的 webview 内核复现。
