### ISSUE TITLE
监控jsonp请求的代码有点问题

### ISSUE THREAD

**Issue by fa-ge** [liriliri/eruda#44]
this._scriptObserver.observe(document.body, { childList: true });
如果有人在head标签中直接初始化eruda,那么这段代码会报错，因为此时body还没有

**Comment by surunzi** [comment]
嗯，这块代码后面会重整

**Comment by fa-ge** [comment]
非常期待，已经把这个插件用到了活动页模板里了，现在部门里几乎所有的新项目都会用到这个插件，希望越做越好。
