### ISSUE TITLE
Use getboxQuads API in Firefox, and polyfill in chrome

### ISSUE THREAD

**Issue by jogibear9988** [liriliri/eruda#443]
Hello, I work on a polyfill for the boxQuadsApi: https://github.com/jogibear9988/getBoxQuadsPolyfill

With this you can draw the correct overlay also on transformed elements. I'm currently working on 3D transform support (wich does not work correctly atm.

SVG and MathML could not be polyfilled completely, cause of missing offsetLeft and offsetTop.

**Comment by jogibear9988** [comment]
?? why closed?

**Comment by surunzi** [comment]
I found that this api is very new and almost no browsers support it.

**Comment by jogibear9988** [comment]
the spec is nearly 10 years old. 
but yes, only firefox supports it, and only with a flag.

but you could use my polyfill, and then you have support for it, this is the thing I meant.
