### ISSUE TITLE
CDN loading is slow

### ISSUE THREAD

**Issue by xuzhuxin** [liriliri/eruda#454]
Introducing CDN into the project. The slow loading of the CDN affects project performance

**Comment by surunzi** [comment]
I'm not quite sure what you mean.

**Comment by xuzhuxin** [comment]
It is introduced through CDN http://cdn.bootcss.com/eruda/1.5.2/eruda.min.js The loading and response time of JS files is very long

**Comment by surunzi** [comment]
That's a CDN issue and is unrelated to this project.
