### ISSUE TITLE
Document body font color inherited into application

### ISSUE THREAD

**Issue by MasterInQuestion** [liriliri/eruda#459]
E.g. &#x60;`<body style="color: #F00">`&#x60; [ Or: [https://berkshirehathaway.com/](https://berkshirehathaway.com/) ]
    Into "Network", "Resources", "Info" tabs.

    Fix proposed:
    Applying specific styles on Eruda components.
    Rather than inherit.

**Comment by MasterInQuestion** [comment]
Likely fix:
    [ https://github.com/liriliri/eruda/commit/600ea6213aa6e6fd8ce03b4c2e1a178be1947ca7](https://github.com/liriliri/eruda/commit/600ea6213aa6e6fd8ce03b4c2e1a178be1947ca7)

**Comment by surunzi** [comment]
v3.4.0 fixes this issue.
