### ISSUE TITLE
can not show cookie

### ISSUE THREAD

**Issue by abcdGJJ** [liriliri/eruda#46]
I find a thing that console panel can not output cookie when cookie is very long.Is it a bug?

**Comment by surunzi** [comment]
What's the content of your cookies?

**Comment by abcdGJJ** [comment]
`
'field="UID=1233&UN=username&TT=12333&PBODY=dhaaaaaadzhhauqqqqqqqqqaddqhqhddhaqiueueuqyeyeqqdqq&VER=1"'
`

like that，also in resource panel cookie is not completed

**Comment by surunzi** [comment]
I don't see anything special about this cookie string. Is it set by browser or server? Cookies set by server with http only option enabled could not be read by client side script.
