### ISSUE TITLE
Misuse of "user-select: none"?

### ISSUE THREAD

**Issue by MasterInQuestion** [liriliri/eruda#461]
I do not understand the purpose of such restriction:
    Why is everything under ".eruda-container" applied ["user-select: none"](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select)?
    Which has caused many undesirable effects.
    E.g. "Elements" tab mostly unselectable normally.

    I configured the browser to ignore alike directives most of the time:
    And don't quite understand why Eruda needed it?
\
\
    See also:
    [ https://github.com/liriliri/eruda/issues/71](https://github.com/liriliri/eruda/issues/71)
    [ https://github.com/liriliri/eruda/issues/142](https://github.com/liriliri/eruda/issues/142)

    Off-Topic:
    uBO workaround:
    `*##*:style( user-select: text !important; -moz-user-select: text !important; -webkit-user-select: text !important; )`

**Comment by surunzi** [comment]
It's done on purpose, I prefer not all things are selectable personally.

**Comment by MasterInQuestion** [comment]
Well... then caveat the potential breakages.
    The "Elements" tab is a notable one: frequently the need to copy the styles etc. element information.

**Comment by MasterInQuestion** [comment]
Up: [ https://github.com/liriliri/eruda/issues/327#issue-1690218288](https://github.com/liriliri/eruda/issues/327#issue-1690218288)

    Note "eruda.util.evalCss" affects the whole page.
    More info: https://eruda.liriliri.io/docs/plugin.html#evalcss
