### ISSUE TITLE
[android chrome browser] does the bookmark method not work anymore?

### ISSUE THREAD

**Issue by RealYukiSan** [liriliri/eruda#469]
I copy the following scripts from [npm pages](https://www.npmjs.com/package/eruda) to the Android Chrome's bookmark bar:

```js
javascript:(function () { var script = document.createElement('script'); script.src="https://cdn.jsdelivr.net/npm/eruda"; document.body.append(script); script.onload = function () { eruda.init(); } })();
```

but after waiting a few seconds, the devtools not pop up :"

**Comment by RealYukiSan** [comment]
What's your browser version?

Here is mine:
![Screenshot_20241022_054054_Chrome](https://github.com/user-attachments/assets/c170a442-63e4-453c-bddb-d12522c6e5d5)

**Comment by CollabVMA50** [comment]
that's a bit newer

**Comment by RealYukiSan** [comment]
Oh yeah, it works, my bad tried to open it on home page lol, I need to go to specific site before open the bookmark.

**Comment by Riders004** [comment]
It's not working for me I have also latest version
