### ISSUE TITLE
显示不正常

### ISSUE THREAD

**Issue by itxuye** [liriliri/eruda#47]
环境React单页应用。
使用:
```
import * as eruda from 'eruda';
eruda.init();
```
结果:
![wechatimg41](https://user-images.githubusercontent.com/9589686/34511566-a055d1b2-f097-11e7-8c79-192f47b63fb1.jpeg)

**Comment by surunzi** [comment]
`alert(eruda.scale()); ` 执行下这个看结果是什么。

**Comment by itxuye** [comment]
@surunzi  3

**Comment by itxuye** [comment]
与我使用rem和淘宝的高清适配方案有关吗

**Comment by surunzi** [comment]
嗯，检测缩放结果不对，初始化后执行下`eruda.scale(1)`看下正不正常。

**Comment by itxuye** [comment]
跟之前截图显示差不多，还是乱在一起

**Comment by surunzi** [comment]
淘宝那个高清适配方案链接发下。

**Comment by itxuye** [comment]
https://github.com/ant-design/ant-design-mobile/wiki/HD

**Comment by surunzi** [comment]
`alert(eruda.util.meta('viewport'));` 执行下这个看结果是什么

**Comment by itxuye** [comment]
![wechatimg42](https://user-images.githubusercontent.com/9589686/34513831-395fc5e0-f0a5-11e7-96f4-b5d685288230.png)

**Comment by surunzi** [comment]
搞个不使用那高清化方案的页面，在同一环境下看看显示是否正常？

**Comment by itxuye** [comment]
@surunzi 不是你的问题，我们的服务器配置了很多安全规则导致的。

**Comment by surunzi** [comment]
嗯，看起来是插件的样式被过滤掉了。
