### ISSUE TITLE
Is it possible to use it with something like loglevel?

### ISSUE THREAD

**Issue by huckym** [liriliri/eruda#475]
Eruda is a super useful tool. The only thing that seems to be the issue is that the information about the source file/line is lost. It all seems to be coming from eruda.js. We have been using loglevel but can't seem to figure out how to get both eruda and loglevel working together so desktop browser still shows the file/line numbers

**Comment by surunzi** [comment]
Eruda captures logs by overriding the console object, which can cause issues when viewing stack information using the browser's actual devtools. If you can view logs using the browser devtools, maybe you shouldn't enable Eruda?

**Comment by huckym** [comment]
@surunzi firstly thanks for your wonderful effort on this project.
Ideally we would like the console on both. While most of our app can be tested on the desktop browser, some states can only occur in the mobile browser. It is okay if we just saw the message on the mobile browser and the stack information in the desktop. Still doesn't make sense? :)

**Comment by surunzi** [comment]
Unfortunately, there is no way to solve this issue as far as I know.  If you just want to see the stack info, you can enable the "Display extra information" setting in the settings panel. Of course, sourcemap is not supported.

**Comment by huckym** [comment]
no worries. Thanks for that extra tip.
Cheers!
