### ISSUE TITLE
有没有监听eruda面板打开的方法

### ISSUE THREAD

**Issue by acmilank22** [liriliri/eruda#50]

**Comment by surunzi** [comment]
有什么使用场景？

**Comment by acmilank22** [comment]
目前我们在使用一个国产的hybrid app的框架。该框架把页头、页尾作为一个主页面，中间的内容部分作为一个iframe嵌进去的，来形成header和footer的固定。

现在我把主页面和iframe都使用了eruda，但是主页面点击eruda的图标后，eruda的面板被iframe遮住了。

所以我想能不能提供一个面板show和hide的监听方法。

**Comment by surunzi** [comment]
好的，目前没有方法可以监听到，下个版本加上，大概一周内发布。

**Comment by acmilank22** [comment]
好的 多谢

**Comment by surunzi** [comment]
可以更新到v1.4.2，使用方法：
```javascript
var devTools = eruda.get();
devTools.on('show', () => console.log('show')).on('hide', () => console.log('hide'));
```

**Comment by acmilank22** [comment]
非常感谢
