### ISSUE TITLE
info面板中的Location块显示的信息并没有及时更新

### ISSUE THREAD

**Issue by fa-ge** [liriliri/eruda#51]
当我无刷新改变地址栏的地址的时候，info面板中的Location块显示的信息并没有及时更新。比如location.hash = ''的方式

**Comment by surunzi** [comment]
嗯，目前不是实时更新的，下个版本改进下。

**Comment by surunzi** [comment]
v1.4.3已发布，面板重新切换时会自动获取新的地址。如果想要实时改变，可以在改变地址时自行调用api进行更新。
```javascript
eruda.get('info').add('Location', location.href);
```

**Comment by fa-ge** [comment]
非常感谢！为什么不像resource面板那样搞个刷新按钮？

**Comment by surunzi** [comment]
Info面板的定位就是展示通用信息的，不做任何复杂操作，里面的地址跟UA显示等也只是几个简单的内置消息。

你可以调用[API](https://github.com/liriliri/eruda/blob/master/doc/TOOL_API.md#info)自行往里面实时更新任何信息。
