### ISSUE TITLE
这个地方有点疑惑

### ISSUE THREAD

**Issue by hold-baby** [liriliri/eruda#54]
![image](https://user-images.githubusercontent.com/21041219/35962688-47141d58-0ced-11e8-8f07-6d8431516123.png)
为何你这样可以
```bable
Error: 'Draggabilly' is not exported by node_modules\_draggabilly@2.1.1@draggabilly\draggabilly.js
```
我这样写就报上面的错？我用的rollup

**Comment by surunzi** [comment]
不清楚，这个应该去rollup的项目提issue。
