### ISSUE TITLE
对 fetch 请求没显示出来返回的response

### ISSUE THREAD

**Issue by jy03078959** [liriliri/eruda#55]
对 fetch 请求没显示出来返回的response
![image](https://user-images.githubusercontent.com/3038488/36651583-85a2af26-1ae4-11e8-9258-2f99186aa4a6.png)

**Comment by surunzi** [comment]
我试了可以，有没有线上demo？

**Comment by Lyfme** [comment]
我也看不到返回的内容，请求用的是isomorphic-fetch
