### ISSUE TITLE
性能不好，log大一点的对象保证可以卡死浏览器

### ISSUE THREAD

**Issue by jasonChen1982** [liriliri/eruda#56]

**Comment by surunzi** [comment]
什么版本？

**Comment by xblxc** [comment]
之前在vue app中打印组件对象，有点卡，不过电脑上也好不到哪去，具体有些忘了

**Comment by surunzi** [comment]
1.4.0版本把计算挪到web worker里了，展示可能一样慢，但应该不会卡住界面了才对，能否看下是哪个版本？ @jasonChen1982 @xblxc

**Comment by jasonChen1982** [comment]
是cocos2d 的 creator 用到的，1.8.1

**Comment by surunzi** [comment]
@jasonChen1982 刚看了下creator 1.8.2已经更新eruda到1.4.3了，可以升级后再试下有没有卡死浏览器的情况发生。

**Comment by daichangxin** [comment]
2020年了，还是有这个问题~

**Comment by surunzi** [comment]
@daichangxin 可以试下 2.0.0 版本
