### ISSUE TITLE
stringifyWork.js 404

### ISSUE THREAD

**Issue by rambo-panda** [liriliri/eruda#57]
版本: 1.4.3

情景:
把eruda放到我们私有cdn上的时候，会出现  `stringifyWork.js` **404**

建议把它打到包里面。或者开发一个`dev`包

**Comment by surunzi** [comment]
那个打到包里了，具体是怎么出现的，跟浏览器有关吗？

**Comment by rambo-panda** [comment]
@surunzi 

![image](https://user-images.githubusercontent.com/2776050/37655234-a9ce0ce0-2c7f-11e8-9619-a804597fa1aa.png)
当浏览器vi'i支持worker的时候。

我暂时关闭了`userWorker`

```js
eruda.config.useWorker = false;
eruda.init();
```

**Comment by surunzi** [comment]
```javascript
eruda.get('console').config.set('useWorker', false);
```
这种情况应该是浏览器支持worker，但又不支持blobUrl时出现，我后面再看下怎么弄好。

**Comment by rambo-panda** [comment]
@surunzi su

ok 期待更新

**Comment by rambo-panda** [comment]
我找到根本原因

我设置了 `Content-Security-Policy` 对于其 `child-src` 没有设置 **"blob:"**
