### ISSUE TITLE
Error: Refused to get unsafe header "Content-Length"

### ISSUE THREAD

**Issue by CocoaHoo** [liriliri/eruda#58]
V1.4.3
get this error again，
![image](https://user-images.githubusercontent.com/6837094/38073473-be3b299e-335d-11e8-8269-2519d2663db4.png)
and I am sure to able cors in my vue spa

**Comment by xblxc** [comment]
https://www.web-tinker.com/article/20686.html

**Comment by xblxc** [comment]
判断是否跨域时出问题了，根源在于fullUrl函数漏掉了一种情况，就是一般我们为了防止在https网站中出现http请求，我们的请求一般是'//api'这样设置

![image](https://user-images.githubusercontent.com/9930402/38304111-d812c296-383a-11e8-9f97-8c75dd808365.png)

**Comment by surunzi** [comment]
@CocoaHoo 可否打下log，看下图中 url 的值是否以 // 开头。
