### ISSUE TITLE
与 browsersync 冲突的问题

### ISSUE THREAD

**Issue by zhuziyi1989** [liriliri/eruda#6]
完全拷贝你的demo，js资源放在本地出现这样的错误：

![http://ww2.sinaimg.cn/large/69b05e0ajw1f47h68mpunj20o10d6gmk.jpg](http://ww2.sinaimg.cn/large/69b05e0ajw1f47h68mpunj20o10d6gmk.jpg)

引用到其他项目也会出现这种情况。

**Comment by surunzi** [comment]
Ajax是不能直接打开使用的。本机起个server就可以正常使用了。

**Comment by zhuziyi1989** [comment]
发现是跟browsersync冲突了。

**Comment by surunzi** [comment]
@zhuziyi1989 请求是browsersync发起的吗？

**Comment by zhuziyi1989** [comment]
对，你可以安装个browsersync试试。

**Comment by surunzi** [comment]
@zhuziyi1989 xhr捕获的实现有点问题，没处理arraybuffer的情况，这两天会修复完善下，可以先在settings面板将xhr捕获的功能给关闭掉。

**Comment by surunzi** [comment]
0.5.8版已修复
