### ISSUE TITLE
跳转到支付宝页面

### ISSUE THREAD

**Issue by wjx600** [liriliri/eruda#60]
不知道什么情况下突然就跳转到支付包的广告页面了

**Comment by surunzi** [comment]
不可能是这个工具引起的吧。。

**Comment by wjx600** [comment]
不知道啊，工具去掉，就不出现，我一直没有找到原因

**Comment by surunzi** [comment]
有线上网址可以复现吗？

**Comment by wjx600** [comment]
暂时没有啊

**Comment by surunzi** [comment]
那没法查

**Comment by wjx600** [comment]
大概是这么样一个地址 ：https://ds.alipay.com/?from=mobilecodec&scheme=alipays%3A%2F%2Fplatformapi%2Fstartapp%3FsaId%3D10000007%26clientVersion%3D3.7.0.0718%26qrcode%3Dhttps%253A%252F%252Fqr.alipay.com%252Fc1x04271vvqxdpeonkwcbd3

**Comment by surunzi** [comment]
有没有那个会跳到广告面的页面？

**Comment by UncleBill** [comment]
会不会是运营商劫持了cdn上的js

RedHoodSu <notifications@github.com>于2018年4月16日 周一16:04写道：

**Comment by surunzi** [comment]
@wjx600 你库用的是 cdn 的地址还是本地路径，有没有用 https？
