### ISSUE TITLE
多台android反复刷新后展示不出来eruda入口

### ISSUE THREAD

**Issue by LightGlobal** [liriliri/eruda#62]
### 环境同步

机型：小米MAX
访问地址： http://eruda.liriliri.io/
浏览器：UC浏览器 V11.9.4.974

### 问题描述

清空浏览器缓存后访问地址，一定会出现eruda入口，但是在反复刷新几次（不超过10次）页面后，eruda入口就不再展示出来。因此我使用了window.onerror捕获页面错误，发现不出现eruda入口的场景，均报了script error错误和Uncaught ReferenceError: eruda is not defined

### 猜测原因

如下方式反复动态eruda.js文件时，可能出现加入的eruda.js内部执行出错而报script error 错误。从而导致eruda引用未注入成功，此时再使用eruda.init 就会报 ReferenceError

```javascript
var script = window.document.createElement('script');
  script.type = 'text/javascript';
  script.src = getUrl(opt.enableHttps);
  script.setAttribute('crossorigin', 'anonymous')
  window.document.head.appendChild(script);
  script.onload = function () {
    eruda.init();
  };
```

**Comment by surunzi** [comment]
1.4.4 版本已兼容。尝试了下，无法在页面离开时销毁 worker，只能在创建 worker 失败时转为不使用 worker 的方案。
