### ISSUE TITLE
点击Elements标签报错了

### ISSUE THREAD

**Issue by zhenhappy** [liriliri/eruda#63]
点击Elements标签报错了, 信息如下
![image](https://user-images.githubusercontent.com/9161946/39391752-099d21c8-4adb-11e8-93a3-afb416d23977.png)

**Comment by surunzi** [comment]
Chrome 是吧

**Comment by CJY0208** [comment]
请问大概多久后会发布修复此问题的新版本？

**Comment by surunzi** [comment]
这周末吧

**Comment by surunzi** [comment]
1.4.4 版本已发布，更新试下 @CJY0208

**Comment by CJY0208** [comment]
非常感谢！ @surunzi
