### ISSUE TITLE
宿主页面的 MutationObserver 回调中使用 console.log 引起死循环

### ISSUE THREAD

**Issue by UncleBill** [liriliri/eruda#65]
`console.log` 被 `eruda` 重写，调用会更新 `eruda-console` 节点，触发宿主的 `MutationObserver `，引起 `console.log`，进入死循环。

```javascript
var observer = new MutationObserver(mutaions => {
  // trigger `eruda-console` DOM Mutation
  console.log('change');
});
```

https://github.com/liriliri/eruda/blob/master/src/Resources/Resources.js#L411-L419

如果用 `iframe` 来隔离应该可以解决： https://github.com/liriliri/eruda/issues/64

或者是否有方法可以拦截宿主页面的 `MutationObserver`，进而绕过 `eruda` UI 的 DOM Mutation

**Comment by surunzi** [comment]
目前可以增加类似下边的代码防止死循环，后续再做处理，应该会采用覆写 MutationObserver 的方案。
```javascript
var observer = new MutationObserver(mutations => {
    var isEruda = false;
    eruda.util.each(mutations, mutation => {
        if (eruda.util.isErudaEl(mutation.target)) isEruda = true;
    });
    if (isEruda) return;
    console.log('trigger');
});
```

**Comment by UncleBill** [comment]
上面的代码和覆写 MutationObserver 的方案我也考虑过，都不是完美的解决方式。前者加入了非用户业务的代码，且用户需要知道这个问题的存在；后者覆写的方案，要求 eruda 在宿主页面的所有脚本前被引用（在原生 MutationObserver 执行之前）。

如果不用 iframe ，我希望用类似 event 的 stopPropagation 的方式，通过鉴别 Mutation 的来源阻止宿主 observer 触发。初步查了下，尚未找到相关资料 😞

**Comment by surunzi** [comment]
还好吧，MutationObserver 业务用到的情况不多，库中使用的一般也都会将 console 相关的代码剥离，不会产生上边的情况。这种极端情况只要能够有办法绕过解决我认为其实还是 ok 的，并不需要做到完美。本身这个工具的定位就只是辅助移动端真机上的 bug 查找而设计的，并不是为了要近可能地接近 Chrome DevTools ，够用就行。

**Comment by surunzi** [comment]
1.5 版本起使用 shadow dom，已经不会有这个问题了。

**Comment by UncleBill** [comment]
🎉
