### ISSUE TITLE
Adding an additional listener on console

### ISSUE THREAD

**Issue by zynga-jpetersen** [liriliri/eruda#66]
Love the library, but I'd like to be able to hook up an additional callback from eruda for each console call so I can log it on a server.

It doesnt look like there is anything like that, but I can hope.

Thanks and again really nice library.

**Comment by surunzi** [comment]
Supported in version 1.4.4.
```javascript
eruda.get('console').on('log', function (val) 
{
    alert(val);
});
console.log('test'); // Alert 'test'
```

**Comment by zynga-jpetersen** [comment]
Thanks! I missed this in the documentation. Thanks!
