### ISSUE TITLE
引用报错ReferenceError: eruda is not defined

### ISSUE THREAD

**Issue by zongyuan-vale** [liriliri/eruda#69]
使用gulp打包的微信网页项目，在微信开发者工具内报错，eruda.js我是放在项目内，非常感谢，如下：

![image](https://user-images.githubusercontent.com/33240274/40756896-60936612-64b8-11e8-98bc-0e4a39092ced.png)

**Comment by surunzi** [comment]
只在微信开发者工具内报错吗？

**Comment by zongyuan-vale** [comment]
在手机上也没用，我是通过微信开发者工具查看后发现这个问题，好的，谢谢

**Comment by surunzi** [comment]
可以先使用未压缩版本的，应该就不会报这个错误了。另外，这个 bug 似乎跟浏览器版本也有关系，我这边无法复现。

**Comment by zongyuan-vale** [comment]
使用cdn或者未压缩就可以正常使用（Use CDN or uncompressed to work properly），谢谢你的帮助

**Comment by hughfenghen** [comment]
似乎跟网站有关系，我通过代理工具注入eruda到网页，js都能正常加载。
https://sh.meituan.com/ 这个初始化成功
https://i.meituan.com/ 报错`eruda is not defined `
猜测，可能是将eruda挂载到全局变量上出问题了。

**Comment by surunzi** [comment]
@hughfenghen https://i.meituan.com/ 设置了 csp

**Comment by hughfenghen** [comment]
@surunzi 我已经把csp重写了，csp生效的时候浏览器不会去下载Eruda js，控制台也不会打印错误。
csp重写后Eruda下载并执行了，才会打印截图的错误。

另外我试了一下将Eruda注入到baidu.com，也会打印错误。可以复现：
访问https://www.baidu.com，打开控制带执行以下代码：
```js
(function () { var script = document.createElement('script'); script.src="//cdn.jsdelivr.net/npm/eruda"; document.body.appendChild(script); script.onload = function () { eruda.init() } })();
```

**Comment by surunzi** [comment]
@hughfenghen  截图错误我没看出来是 eruda.js 执行错误，调用栈里没有看到 eruda 相关的。你从哪里确认 eruda 有下载并执行？有示例地址吗？

**Comment by surunzi** [comment]
百度的我看了下，他是页面使用了 amd 导致的。

**Comment by surunzi** [comment]
看了下，美团的那个也是

**Comment by hughfenghen** [comment]
@surunzi 执行`window.define=undfined`后，能成功注入Eruda。👍

**Comment by hughfenghen** [comment]
广告一下刚写好的代理工具，可以直接将Eruda注入到页面，即使项目没有主动接入Eruda。
[Erra](https://github.com/hughfenghen/erra)
[注入Eruda](https://hughfenghen.github.io/erra/guide.html#%E6%B3%A8%E5%85%A5eruda)
