### ISSUE TITLE
某些页面不能用

### ISSUE THREAD

**Issue by 1217965058** [liriliri/eruda#75]
例如百度搜索，知乎。百度是载入时出错，导致无法获取到eruda变量。知乎是不知道为什么压根就不载入js文件。还请各位大神解惑

**Comment by surunzi** [comment]
百度用了 amd 模块规范，eruda 由于使用了 umd 规范导致直接载入时无法挂载到全局对象上，先执行 `define = null`，然后再插入脚本应该就行了。

知乎是使用了 CSP，具体是什么可以看下 MDN 上的[相关文档](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)。

**Comment by AllanChain** [comment]
考虑把这个问题加进 README？新来的表示直接在 GitHub 项目主页上测试就不成功有点。。烦
