### ISSUE TITLE
希望支持类似weinre -> elements的远程调试DOM/CSS的功能

### ISSUE THREAD

**Issue by yinxin630** [liriliri/eruda#76]

**Comment by yinxin630** [comment]
还有目前的console功能, 也希望能支持远程执行代码, 手机上编写代码不方便

**Comment by surunzi** [comment]
远程调试 DOM，直接使用 weinre？
console 你可以使用 PC 微信之类的传代码到手机，然后复制粘贴。

**Comment by yinxin630** [comment]
![image](https://user-images.githubusercontent.com/6939365/42744901-5a3a28a0-8902-11e8-8e05-2a3c756bb143.png)
现在erada除了没有这个功能, 其它都做的比weinre要好, 如果能支持这个就可以愉快的丢掉weinre了

**Comment by yinxin630** [comment]
又发现一个工具 [vorlon.js](http://www.vorlonjs.io/), 看起来能替代 weinre
