### ISSUE TITLE
移动端适配问题

### ISSUE THREAD

**Issue by myunique** [liriliri/eruda#77]
1. 移动端调试偶然找到这个工具，惊为天人。不过在使用的时候，存在适配问题，调试窗口字体太小了，想问一下有没有更详细的使用教材，或者说怎么调整这个窗口的样式？
![image](https://user-images.githubusercontent.com/21308557/43123987-5e932760-8f58-11e8-925a-8e3c37fe1e73.png)

**Comment by myunique** [comment]
才看到还有其他的文档，eruda.scale(1);这个属性可以调整控制台大小

**Comment by simpleLiYu** [comment]
移动端怎么用的大佬

**Comment by myunique** [comment]
现在移动端适配的很好了，直接引入就可以了

**Comment by myunique** [comment]
我当时用了没多久就没用这个了。如果要用这个的话可以看看这个文档https://github.com/liriliri/eruda/blob/master/doc/API.md
