### ISSUE TITLE
Error: Refused to get unsafe header "Content-Length"

### ISSUE THREAD

**Issue by hanthomas** [liriliri/eruda#8]
What a great tool this is!  For the most part, it works flawlessly.  However, I'm getting a lot of errors from eruda **Refused to get unsafe header "Content Length"**.  My code uses Angular and makes frequent XHR requests.  My guess is that eruda is having trouble inspecting the headers returned by the XHR requests.  Thanks for looking into this.

**Comment by surunzi** [comment]
I remember fixing this bug before. Are you using the latest version?

**Comment by hanthomas** [comment]
@surunzi Yes, I am using 5.9, but I still get this error.

**Comment by surunzi** [comment]
@hanthomas Turns out the try catch block doesn't do the trick. Is the eruda script in the same domain as your page?

**Comment by hanthomas** [comment]
@surunzi Yes, the eruda script is in the same domain. However, the XHR requests are being made to another domain that provides a REST service.  That service is configured to allow CORS requests.  I wonder if the problem is that cross domain XHR requests limit which header values can be inspected even if CORS is enabled.

**Comment by surunzi** [comment]
Yeah, it definitely has something to do with cross domain requests. I'll try to see if there's a way to bypass it. Thanks for reporting the issue:)

**Comment by surunzi** [comment]
@hanthomas Try v0.6.0

**Comment by hanthomas** [comment]
@surunzi That fixed it.  Thanks!
