### ISSUE TITLE
Uncaught DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest'

### ISSUE THREAD

**Issue by defghy** [liriliri/eruda#82]
env:
`vue-resource`
config:
`Vue.http.options.responseType = 'json';`
error:
`Uncaught DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json').
    at eval (eval at value (http://cdn.jsdelivr.net/npm/eruda:2:275427), <anonymous>:1:3)
    at t.value (http://cdn.jsdelivr.net/npm/eruda:2:275427)
    at XMLHttpRequest.<anonymous> (http://cdn.jsdelivr.net/npm/eruda:2:271445)`
error trace:
![image](https://user-images.githubusercontent.com/5386958/43443149-a5601bec-94d2-11e8-816c-05f0a6622b2c.png)
![image](https://user-images.githubusercontent.com/5386958/43443184-bbdb38b6-94d2-11e8-9db9-571b32bac75f.png)
![image](https://user-images.githubusercontent.com/5386958/43443213-cf26e14a-94d2-11e8-839d-edc19f2256e4.png)

**Comment by surunzi** [comment]
1.5.1 版本已修复。
