### ISSUE TITLE
能否提供api来获取工具面板里的信息？

### ISSUE THREAD

**Issue by lili21** [liriliri/eruda#83]
比如[Info](https://github.com/liriliri/eruda/blob/master/doc/TOOL_API.md#info)

```javascript
const info = eruda.get('info')

info.get() // 返回info内容
```

类似于这样的api。

虽然可以通过`info._infos`获取，但感觉不是很直观。

**Comment by surunzi** [comment]
1.5.1 版本已发布，支持获取信息。
```javascript
const info = eruda.get('info')
info.add('title', 'content')
info.get(); // -> [{name: 'title', val: 'content'}]
info.get('title') // -> 'content'
```

**Comment by lili21** [comment]
这个是只加了Info吗？我只是以info做个例子，应该其他的也加一下对于的接口？console, network, resources。

**Comment by surunzi** [comment]
只加 info，列举的其它那些自己重写下相关方法就能拿到了吧。
