### ISSUE TITLE
更好的插件开发文档

### ISSUE THREAD

**Issue by lili21** [liriliri/eruda#84]
目前想要自己开发一个插件的话，除了用`eruda-plugin`生成一个之外就没有任何信息了。

剩下的都要靠自己去看其他插件的源码来理解发生了什么。

是不是可以介绍一下，插件有哪些部分组成，分别用来做什么？

**Comment by surunzi** [comment]
已加 https://github.com/liriliri/eruda/blob/master/doc/PLUGIN.md
