### ISSUE TITLE
network

### ISSUE THREAD

**Issue by bihongbin3027** [liriliri/eruda#86]
我点到network选项卡里面，页面切换不出来网络请求，请问是什么原因呢

**Comment by surunzi** [comment]
有示例页面？

**Comment by bihongbin3027** [comment]
@surunzi 关注一下“康美云o2o商城“公众号，我把这个工具加到里面了，打开就可以看到 ，并没有显示网络请求

**Comment by surunzi** [comment]
页面引用了 **pace.js**，这个插件同样会覆盖 **XMLHttpRequest** 对象来监听请求从而导致 eruda 监听不了原生对象。把 `eruda.init()` 放到加载 **pace.js** 之前应该就可以了。

**Comment by bihongbin3027** [comment]
好的 谢谢
