### ISSUE TITLE
Toggle switches in Settings are very difficult to use

### ISSUE THREAD

**Issue by hanthomas** [liriliri/eruda#9]
I noticed that the toggle switches in the Settings tab don't respond very well to either taps (or clicks in desktop browser).  I have tap on them several times in order to get it to change state.  All other UI interactions work just fine... just these toggle switches are not very responsive.  My app has code to optimize touch/click events, so I suspect this might be interfering with these toggles.  Any chance the toggles could just be changed to ordinary checkboxes?

**Comment by surunzi** [comment]
Are you using libraries like fastclick or you write something similar yourself?

**Comment by surunzi** [comment]
Found a solution here: https://github.com/ftlabs/fastclick/issues/90
I tried it with fastclick, and it works just fine.
@hanthomas Download v0.5.9, and see if it's still hard to toggle the switches.

**Comment by hanthomas** [comment]
@surunzi Thanks for your quick response.  This is working perfectly now.
