### ISSUE TITLE
When type "window" in console panel and expand the result object, broswer crash.

### ISSUE THREAD

**Issue by lavyun** [liriliri/eruda#92]
When type "window" in console panel and expand the result object, broswer crash.

**Comment by lavyun** [comment]
Is the reason why the window object is too large?

**Comment by surunzi** [comment]
Where on the platform does it happen?

**Comment by lavyun** [comment]
ios 12, safari. Most browsers become stuck when expanding a large object, like ‘window’.

**Comment by surunzi** [comment]
I tried it with ios 12.0 on the [demo](https://eruda.liriliri.io/) page, nothing wrong.

**Comment by surunzi** [comment]
Try 1.6.1, see if it still crashes.
