### ISSUE TITLE
使用了eruda, ios safari在页面内点击一个pdf的文件链接，后退的时候，刷新了页面

### ISSUE THREAD

**Issue by kind-hearted** [liriliri/eruda#97]
ios safari在页面内有一个pdf的文件链接
伪代码
```html
<a href="./example.pdf">example.pdf</a>
```
没有使用eruda的时候，点击链接再返回页面，页面不会刷新。
使用了eruda，页面会刷新。
不知道为什么需要刷新，是否可以禁止eruda返回的时候刷新页面。
因为在uat测试的时候，我们通常会使用eruda，以方便测试出现BUG的时候，能查看到报错或请求相关信息。
在上线的时候将eruda去掉，刷新的话会带来副作用，比如表单填写信息丢失，无法正常测试。

**Comment by surunzi** [comment]
无法重现
